src/rviz/mesh_loader.cpp
Addresses issue #836
Before:
After:
=> change the default ambient color to 0's

src/rviz/default_plugin/path_display.cpp, src/rviz/default_plugin/path_display.h
This adds a new display style called "Billboards" to the Path display, similar to how it is implemented for the Grid display. For the "Billboards" style, the line width can be adjusted, which implements enhancement request #650 and is helpful when e.g. displaying paths using a projector. The old display style "Lines" is preserved and left untouched for backwards compatibility.
I also added an "Offset" property to the Path display, that allows to shift the displayed path in relation to the origin of the fixed frame. Useful to e.g. shift the Z coordinate when displaying lots of information in Rviz that otherwise overlaps.
=> Adjustable line width for Path display + offset property

src/rviz/default_plugin/tools/selection_tool.cpp, src/rviz/tool.cpp, src/rviz/tool.h, src/rviz/tool_manager.cpp, src/rviz/tool_manager.h, src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h
The current shortkey handling for RViz Tools is quite rigid, since it prevents tools from internally using shortkeys that overlay those defined to switch between tools. An issue, I stumbled across various times now and always worked around by choosing 'free' keys, but since those are limited, I would like to a) start a general discussion on the handling of shortkeys and get an idea what the community/the maintainers think about this issues, b) propose a minimal invasive patch that extendes the shortkey handling and c) offer my help to work out a proper shortkey handling.
a) General Discussion
I checked the source code an realized that the shortkeys that call a Tool are placed within the QActions which represent the Tools in the Toolbar and that if a shortkey is pressed the Toolbar …
=> allow tools to get access to any keyevent

src/rviz/mesh_loader.cpp
I've been bringing up a new robot in RVIZ/Gazebo using Collada meshes and URDF and have found that it was nearly impossible to get the meshes to look remotely similar within Gazebo and RVIZ. If the robot looked OK in Gazebo it was washed out in RVIZ, if it was OK in RVIZ it was too dark in Gazebo.
Searching the RVIZ codebase for "setAmbient" shows that almost always the r,g,b values have been scaled by 0.5 (not sure why). As soon as I add this commit, I no longer get washed out collada files (Tested with both my new robot and the PR2). This commit does not change anything for users specifying pure STL files or OGRE mesh files, only Collada users.
This is a potential solution for https://github.com/ros-visualization/rviz/issues/515
=> scale ambient by 0.5 for collada and other assimp-loaded resources

src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h
As per subject.
Now I don't have to scroll back in the console all the time (working with multiple workspaces).
I thought about adding the version to the window title, but that seemed a bit involved for now.
I'm afraid I've only been able to test this on Ubuntu Precise.
=> Add a simple 'About' dialog to the help menu.

src/rviz/ogre_helpers/mesh_shape.cpp
MAJOR leak: no meshes are ever destroyed without removing the mesh from
the mesh manager. This gets really bad when drawing meshes with 50K
triangles at 10Hz (leak @ ~60MB/sec).
=> ogre_helpers: Fixing mesh memory leak

src/rviz/ogre_helpers/mesh_shape.cpp
MAJOR leak: no meshes are ever destroyed without removing the mesh from
the mesh manager. This gets really bad when drawing meshes with 50K
triangles at 10Hz (leak @ ~60MB/sec).
**NOTE: THIS IS AN UNTESTED CHERRY-PICK**
=> ogre_helpers: Fixing mesh memory leak (untested cherry-picked to indigo)

src/rviz/tool.cpp, src/rviz/tool_manager.cpp, src/rviz/tool_manager.h
* initialized the shortcut_key_ param with '/0' to be able to check whether a tool has a shortkey assigned or not
* made the tool manager check if a tool has a shortkey before converting the char to a key code
* (hopefully) fixed the toKeys method by removing the assertions, making at a boolean returning function and allowing a single key only,
as this is what is to be expected from the shortcut_key_ param
this should fix #851
=> init tool's shortcut_key_ and fixed toKeys()

src/rviz/tool_manager.cpp, src/rviz/tool_manager.h, src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h
i stumbled upon a minor issue while creating a tool that behaves like a trigger. in the rare case where a tool invokes another tool during it's activation the gui becomes inconsistent. 
then i found that there's no method to redraw a tool's icon and text in the toolbar, so i wrote a small refresh method.
=> minor gui improvements

src/rviz/default_plugin/wrench_display.cpp, src/rviz/default_plugin/wrench_display.h, src/rviz/default_plugin/wrench_visual.cpp, src/rviz/default_plugin/wrench_visual.h
since force and torque are different quantities, the units of their scalings are different (meters per Newton and meters per Newton-meter, respectively), and so they should really have separate scalings. Practically, the torques in my Wrench are usually much smaller than the forces if I use the same scaling.
I am on Groovy, but it looks like this patch can apply to all releases up to present.
=> Allow force and torque in Wrench to be scaled separately

src/rviz/default_plugin/marker_display.cpp
Currently if you send a DELETE or DELETE_ALL with no `header.frame_id`, or an untransformable `header.frame_id`, the deletion does not happen. There is no reason to need the `frame_id` for delete, we should go ahead and do the delete anyways (MoveIt uses a similar logic in the tf filter fail for object insertion/deletion).
Probably also fixes what @JessChL was seeing in #865
=> deleting markers does not require transform

src/rviz/robot/robot.cpp
On my environment, sometimes rviz crashes because of setting nan transformation of robot links.
This patch checks if robot links transformation contains NaNs and when they include NaNs, skip updating transformations of links.
```
Program received signal SIGABRT, Aborted.
0x00007ffff62970d5 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) where
#0  0x00007ffff62970d5 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff629a83b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff628fd9e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff628fe42 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff3630ae6 in Ogre::Node::setPosition(Ogre::Vector3 const&) ()
from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.7.4
#5  0x00007ffff7a9937e in …
```
=> Check if position and orientation of links of robots contain NaNs when updating pose of robot links

src/rviz/default_plugin/point_cloud_common.cpp
Otherwise, given a stream of clouds with some of them empty, the last
non-empty message will still be displayed until a the next non-empty cloud
comes in.
=> also process empty pointclouds

CMakeLists.txt
Otherwise it might happen that catkin (and the rest of the workspace) uses 2.x
and rviz detects & tries to use 3.x. This can produce some nasty collisions.
See rospack, roslz4, qt_gui_cpp and others for similar invokation.
=> find_package python version detected by catkin

src/rviz/default_plugin/markers/mesh_resource_marker.cpp, src/rviz/default_plugin/markers/mesh_resource_marker.h
Reinstated original form of mesh tinting and removed color pass technique that was introduced in #752. The color pass technique was overriding mesh texture and alpha values. It appears that the issue present in #751 was actually a result of a piece of code that would make a mesh pure white if the message sent rgba values of 0000. I can't pinpoint why, but I estimate that somehow that was erroneously turning collada markers pure white. Tested change with rviz/src/test/mesh_marker_test.cpp and ran several tests with collada markers, using mesh_use_embedded_materials true and false. Transparency and mesh tinting appear to work as desired.
=> Fix mesh alpha tinting

src/rviz/default_plugin/tf_display.cpp
#888 
The tf plugin is not written using tf2. It was not display static tf frame collectly.
To fix this problem, treat ros::Time(0) which return from getLatestCommonTime() as static frame.
test
-----
1. publish static and dynamic frames.
```
$ rosrun tf2_ros static_transform_publisher 0 0 1 0 0 0 1 map frame_static
```
```
$ rosrun tf static_transform_publisher 0 1 0 0 0 0 1 frame_static frame_dynamic 20000
```
2. Check it in rviz. 
Map frame and frame_static will not be vanished.
=> Fix #888: TF plugin handles static transform of tf2.

src/rviz/default_plugin/point_cloud_common.cpp, src/rviz/default_plugin/point_cloud_transformers.cpp
@calderpg point in #885 a select handler class which wasn't the right place to look but has a bug too. So I fix it with commit f331536 for rgb and add a case for rgba.
2db2f79 fix the display of the pointcloud by handling rgba directly in rgb RGB8Transformer.
I duplicate the _for_ to avoid garbage value in the first octet (alpha) of rgb to be used as alpha when alpha property or pointcloud is under 1.
Finally, 6cd4607 enable a per pixel alpha for rgba. But this seems a bit odd way to do. I'll be glad to hear comments or suggestions.
To test setup a PointCloud2 rviz pluggin with size property set to at least 0.2. 
There will be 2 points in (0,0,0) in red alpha=255 and (0.5,0,0) in green alpha=100. 
Add a Selection Panel to test f331536.
```
cat << EOF | rostopic pub /points …
```
=> Issue #885: display Pointcloud2 with rgba field and handle per pixel alpha.

plugin_description.xml, src/rviz/default_plugin/CMakeLists.txt, src/rviz/default_plugin/view_controllers/third_person_follower_view_controller.cpp, src/rviz/default_plugin/view_controllers/third_person_follower_view_controller.h, src/rviz/frame_position_tracking_view_controller.cpp, src/rviz/frame_position_tracking_view_controller.h
This new view controller follows a target frame. In contrast to XYOrdbit the camera also turns with the target frame. This could be handy if you are doing 3D mapping of a hallway with corners for example.
=> Third person follower view controller

src/rviz/display.cpp
Otherwise the state between Panel & Display becomes inconsistent.
Fixed symptom: When loading a configuration that contains a disabled
CameraDisplay, during the configuration of the panel(the camera render
widget), the panel is set visible for a very short period of time. Because of
the missing logic, the CameraDisplay is enabled together with the panel, but
the Display remains enabled after the Panel is set invisible. One ends up with
an enabled
(and subscribed) CameraDisplay without the corresponding RenderWidget, even so
the configuration specified that the Display is _not_ enabled.
=> disable Display if associated Panel becomes invisible

src/rviz/default_plugin/map_display.cpp, src/rviz/default_plugin/map_display.h
Map displays previously only updated when receiving a message. This means that
if your fixed frame was base_link, the costmaps would not move appropriately
around the robot unless a message was received in order to update the transform
that should be applied to the scene. For global costmaps, this is a slow
update and for static maps, this never happened.
This fixes that by hooking into rviz' periodic call to continuously update the
transform to be applied to the scene.
=> Smooth updates for map display plugin

src/rviz/ogre_helpers/stl_loader.cpp
As a follow up to #920, this PR adds a small change to one of the printed messages that displays when a file contains less data than is suggested by its triangle count. The message now correctly indicates that the triangle count is a 32 bit integer.
=> Updated warning message to indicate triangle count is 32bits

src/rviz/default_plugin/tf_display.cpp
Do not needlessly delete tree_property_ elements, update them instead.
See #911 for details.
Most likely fixes #808 too.
=> Fix #911 #616 : TF Segfaults on reset/update

CMakeLists.txt
... instead of using a hard-coded pkg-config to make cross-compiling
possible where the pkg-config binary is host-prefixed (e.g.
armv7-unknown-linux-pkg-config when cross-compiling for armv7)
=> build: Use PKG_CONFIG_EXECUTABLE

src/rviz/display_group.cpp, src/rviz/properties/property.cpp
I ran rviz with a debug build of Qt, and it crashed with an assertion failure.  This fixes that failure.
A normal (release) build of Qt has the assertions disabled, so this doesn't happen in normal use.
The assertion fails when any of these values are zero and the code continues.  You end up with a first = 5, last = 4 situation inside QAbstractItemModel::beginRemoveRows(), which triggers an assertion that first <= last.
=> Fixed Qt assertions triggered in debug build of Qt.

src/rviz/default_plugin/map_display.cpp
Without this patch, the map display shows frame transformation errors
from with an empty frame_id, since it attempts to transform the 
default-initialized occupancy grid variable.
=> Don't attempt to `transformMap` until one is actually received.

src/rviz/ogre_helpers/billboard_line.cpp
Fix for https://github.com/ros-visualization/rviz/issues/941
=> Fixed billboard line generation for zero key points

CMakeLists.txt
The plugin is handled by pluginlib. Exporting it creates an unneeded dependency in rvizConfig.cmake.
=> Remove default_plugin from exported libraries

src/rviz/ogre_helpers/render_system.cpp
This PR is an attempt to truly enable antialiasing. The only piece of code that seemed related to it was [here](https://github.com/ros-visualization/rviz/blob/4abbbd9a413ee26942d1c7d838975d58b3cc0434/src/rviz/ogre_helpers/render_system.cpp#L241-L242), but changing the value did not seem to have any effect. I added the entry to the proper dictionary, and used a value of 4 which is quite common (cf. [Gazebo](https://bitbucket.org/osrf/gazebo/src/38fbac52640382b2f7ff749aca3580cca7fd7994/gazebo/rendering/WindowManager.cc?at=default&fileviewer=file-view-default#WindowManager.cc-91)). Talking about Gazebo, they also [added antialiasing to their `Camera` class](https://bitbucket.org/osrf/gazebo/src/38fbac52640382b2f7ff749aca3580cca7fd7994/gazebo/rendering/Camera.cc?at=default&fileviewer=file-view …
=> Enable antialiasing

src/rviz/ogre_helpers/render_system.cpp, src/rviz/ogre_helpers/render_system.h, src/rviz/visualizer_app.cpp
Follow up for https://github.com/ros-visualization/rviz/pull/931
=> add an option to disable AA

src/rviz/default_plugin/tf_display.cpp, src/rviz/default_plugin/tf_display.h
This is a fix for issue [#834](https://github.com/ros-visualization/rviz/issues/834) using the changes from PR [#938](https://github.com/ros-visualization/rviz/pull/938) by @arntanguy with the following modifications:
1. Rather than adding a new frame and setting the enabled state of the frame immediately when reading the config, the enabled state for each specified frame is stored in a map.
2. Whenever a frame is being added to the display it looks up its enabled state in the map, and if it was configured as disabled the frame is set to be disabled.
Because no new frames are created when loading the config this properly handles the case where frames specified in the config file are not published at the time the config is read mentioned in PR …
=> Fix for tf display not loading frame config

src/rviz/default_plugin/map_display.cpp
Color for lethal obstacle values for the obstacle map display is yellow, not purple.
=> Minor map color documentation fix in map_display.cpp

src/rviz/properties/splitter_handle.cpp
SplitterHandle (for PropertyTreeWidget) only reacted on `resize` events. However, when
the columns where resized externally or scrolling happened (e.g. in MoveIt's MotionPlanning display)
the splitter wasn't correctly shifted.
Intercepting all `Paint` events, one can react to those situations as well.
Further, I use `updateGeometry()` in constructor too, thus having a single location calling `setGeometry()`.
Finally, `paintEvent` adds an additional offset of 1 to deal with QTreeView's `viewport margin`, thus now perfectly matching the cell boundary.
The new code was thoroughly tested with the following simple main.cpp:
```cpp
#include <QTreeView>
#include <QStandardItemModel>
#include <QStyledItemDelegate>
#include <QPainter>
#include <QApplication>
#include <splitter_handle.h>
class …
```
=> fixed SplitterHandle of PropertyTreeWidget

src/rviz/display.cpp
... when no statuses where created beforehand
=> fix crash on Display::deleteStatus()

src/rviz/default_plugin/map_display.cpp
This allows map pixel values to be passed directly through and drawn as-is in grayscale.
This will be especially useful in combination with ros-planning/navigation#422
=> Adding raw mode for map vizualization

src/rviz/message_filter_display.h
Added "Unreliable hint" option to base MessageFilterDisplay template
class.
This allows the user to choose the option to use UDP unreliable [TransportHints](http://docs.ros.org/hydro/api/roscpp/html/classros_1_1TransportHints.html) for high throughput topics in a bandwidth constrained environment where TCP retransmits cause more congestion.
Verified that saving the rviz config shows `Unreliable: true` for topics selected with the option.
Also verified in wireshark that UDP is correctly used for topics selected and publishers that support it.
=> Add checkbox to hint for unreliable (UDP) topic transport for DisplayFilter based plugins.

src/rviz/viewport_mouse_event.h
ViewportMouseEvent is forward declared as a class in other headers, which causes warnings in clang with -Wmismatched-tags
=> Convert to class

src/rviz/ogre_helpers/billboard_line.cpp
Fixing a bug in the BillboardLine class when setting up the chains. The case where the number of points is an exact multiple of 16384 (MAX_ELEMENTS) was not being handled and resulted in the number of chains being set to 0 which results in ogre throwing the following exception:
terminate called after throwing an instance of 'Ogre::ItemIdentityException'
what():  OGRE EXCEPTION(5:ItemIdentityException): chainIndex out of bounds in BillboardChain::addChainElement at /build/buildd/ogre-1.8-1.8.1+dfsg/OgreMain/src/OgreBillboardChain.cpp (line 243)
This issue has been mentioned in: [ORB_SLAM issue 60](https://github.com/raulmur/ORB_SLAM/issues/60), [ORB_SLAM issue 21](https://github.com/raulmur/ORB_SLAM/issues/21), [hratc2015_framework issue …
=> Fix for chainIndex out of bounds in BillboardChain::addChainElement

src/rviz/properties/property.cpp, src/rviz/properties/property_tree_delegate.cpp
A read-only property shouldn't be allowed to be edited ;-)
Fixed by not creating an editor in that case.
Related #654 which attempted to solve that issue by disabling the property,
which in turn was reverted in #679 due to its side effects.
=> Make read-only properties read-only

src/rviz/default_plugin/marker_display.cpp, src/rviz/default_plugin/marker_display.h
The marker display does not currently load the enabled/disabled state of namespaces from its config. Those values are simply not used. These changes load the enabled/disabled state of namespaces from the config into a map which gets used to disable namespaces when they are added.
This is essentially the same fix as commit 0baa9f351cb73f880141ecfabd61aaa224de7458 but applied to the marker display instead of the tf display.
=> Updated the marker display to allow namespaces to be enabled/disabled from the config

CMakeLists.txt
CMake prints the following warning:
```
-- checking for module 'eigen3'
--   found eigen3, version 3.2.0
CMake Warning at /opt/ros/jade/share/cmake_modules/cmake/Modules/FindEigen.cmake:62 (message):
The FindEigen.cmake Module in the cmake_modules package is deprecated.
Please use the FindEigen3.cmake Module provided with Eigen.  Change
instances of find_package(Eigen) to find_package(Eigen3).  Check the
FindEigen3.cmake Module for the resulting CMake variable names.
Call Stack (most recent call first):
CMakeLists.txt:130 (find_package)
-- Found Eigen: /usr/include/eigen3  
-- Eigen found (include: /usr/include/eigen3)
```
Replacing `Eigen` with `Eigen3` as proposed by the warning message works for me (Ubuntu 14.04.3 LTS).
=> Fix CMake warning about FindEigen.cmake being deprecated. 

src/rviz/default_plugin/map_display.cpp, src/rviz/default_plugin/map_display.h, src/rviz/image/image_display_base.cpp, src/rviz/image/image_display_base.h
When streaming videos it's usually a good idea to do it using UDP. This is specially true if we are connected through Wi-Fi or other "unreliable" connection.
Since we were having problems visualizing the streams coming from our robot over Wi-Fi, we decided to make the **Unreliable** (UDP) option also available for **Image** and **Camera** displays. We also made it available for Map.
=> Unreliable option on image, camera and map

src/rviz/default_plugin/interactive_markers/interactive_marker_control.cpp, src/rviz/default_plugin/interactive_markers/interactive_marker_control.h
Initial fix for #959: jumping interactive marker in MOVE_3D mode.
I need to check whether other modes are affected too.
=> fix #959: jumping marker in MOVE_3D mode

src/rviz/displays_panel.cpp, src/rviz/displays_panel.h
Demo: https://youtu.be/FxUOrkBzVzs
**1**
**2**
**3**
=> Add "Duplicate" button to duplicate display with same config

CMakeLists.txt, src/CMakeLists.txt, src/image_view/CMakeLists.txt, src/rviz/CMakeLists.txt, src/rviz/add_display_dialog.cpp, src/rviz/default_plugin/CMakeLists.txt, src/rviz/display_factory.cpp, src/rviz/main.cpp, src/rviz/ogre_helpers/render_system.cpp, src/rviz/ogre_helpers/render_widget.cpp, src/rviz/ogre_helpers/render_widget.h, src/rviz/properties/property.cpp, src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h, src/rviz/visualizer_app.cpp, src/rviz/visualizer_app.h, src/test/CMakeLists.txt, src/test/color_editor_test.cpp, src/test/line_edit_with_button_test.cpp
I rebased and squashed @simonschmeisser's commits in https://github.com/ros-visualization/rviz/pull/909. I'll also be cherry-picking over my fixes for the splash screen and stuff like that.
This will replace https://github.com/ros-visualization/rviz/pull/909.
=> port rviz to Qt5 with continued support for Qt4

src/rviz/default_plugin/marker_display.cpp, src/rviz/default_plugin/tf_display.cpp
Updated the marker display and tf plugins to update the map of enabled namespaces and frames whenever those frames are enabled/disabled using the check boxes. Also updated the plugins so that the map of enabled namespaces and frames does not get erased whenever the plugin is reset.
This allows the currently selected namespaces/frames to remain selected after the Reset button is pressed.
=> Updated the marker display and tf plugins to not reset enabled namespaces/frames

src/rviz/default_plugin/wrench_display.cpp, src/rviz/default_plugin/wrench_display.h, src/rviz/default_plugin/wrench_visual.cpp, src/rviz/default_plugin/wrench_visual.h
This PR attempts to increase code-reusability for `rviz::WrenchStampedVisual`, which is currently used by the wrench display plugin.
The visual itself doesn't handle or use the timestamp. Hence I suggest to:
- change the API of `setMessage()` to accept a `geometry_msgs::Wrench` 1c341c0
- rename `setMessage()` to `setWrench()` 1c341c0
- add an additional method `setWrench(Vector3 force, Vector3 torque)` 24e4bab
Furthermore, I modified the code to allow for
- hiding the markers e78ebee
- auto-hiding the force or torque marker if their magnitude becomes too small (which created strange artifacts in existing code) 7a51333
=> generalize WrenchVisual

src/rviz/default_plugin/wrench_display.cpp, src/rviz/default_plugin/wrench_display.h, src/rviz/default_plugin/wrench_visual.cpp, src/rviz/default_plugin/wrench_visual.h
Thanks for merging the #982. This is the cleanup for Kinetic, removing the deprecated code and renaming WrenchStampedVisual to WrenchVisual.
=> cleanup WrenchVisual

CMakeLists.txt, plugin_description.xml
Fixes https://github.com/ros-visualization/rviz/issues/1003
=> update the plugin_description.xml to reflect the new default plugin library name

CMakeLists.txt, package.xml, src/rviz/default_plugin/depth_cloud_mld.cpp
This would avoid issues with linking against OpenCV on Jessie which uses Qt4. It looks like the process may have already been done, but the dependencies were never removed?:
From https://github.com/ros-visualization/rviz/blob/kinetic-devel/src/rviz/default_plugin/depth_cloud_mld.cpp#L137-L139:
>     // The following computation of center_x,y and fx,fy duplicates
// code in the image_geometry package, but this avoids dependency
// on OpenCV, which simplifies releasing rviz.
=> change rviz to no longer use opencv

CMakeLists.txt, src/image_view/CMakeLists.txt, src/rviz/CMakeLists.txt, src/rviz/default_plugin/CMakeLists.txt, src/test/CMakeLists.txt
Unify QT usage in cmake files for both Qt4 and Qt5 version by setting _common_ variables once.
=> cmake qt5 cleanup

src/rviz/default_plugin/CMakeLists.txt
I had some issues switching between `kinetic` and `indigo` branch in my workspace: Both use different names of the `default_plugin` lib, written by the custom target `create_default_plugin_location_file`.
However, cmake's `add_custom_command` only evokes the file-writing command if the output file to be created is not yet there (or older than dependencies). So, it's never rewritten as there is no dependency.
Using `COMMAND` directly in `add_custom_target` solves that issue.
The same patch should be applied to `kinetic`.
=> always (re)create default_plugin_location.cmake

src/rviz/default_plugin/effort_display.h
While compiling rviz from source on Arch with gcc 6.1.1, got errors like the following:
```cpp
In file included from /opt/ros/kinetic/include/tf/transform_datatypes.h:44:0,
from /opt/ros/kinetic/include/tf/time_cache.h:38,
from /opt/ros/kinetic/include/tf/tf.h:43,
from /opt/ros/kinetic/include/tf/transform_listener.h:38,
from [..]/src/rviz/src/rviz/default_plugin/effort_display.cpp:4:
[..]/src/rviz/src/rviz/default_plugin/effort_display.h: In destructor ‘virtual tf::MessageFilterJointState::~MessageFilterJointState()’:
[..]/src/rviz/src/rviz/default_plugin/effort_display.h:39:37: error: unable to find string literal operator ‘operator""fmt’ with ‘const char [28]’, ‘long unsigned int’ arguments
ROS_DEBUG_NAMED("message_filter", "MessageFilter [target=%s]: "fmt, …
```
=> Fix compile error due to the user-defined string literals feature

src/rviz/display.h, src/rviz/external/resource_retriever.h, src/rviz/mesh_loader.cpp, src/rviz/ogre_helpers/grid.cpp, src/rviz/ogre_helpers/line.cpp, src/rviz/ogre_helpers/shape.cpp, src/rviz/properties/property.h, src/rviz/robot/robot_link.cpp, src/rviz/tool.h, src/rviz/view_controller.h
This PR fixes compilation warnings (all of them with gcc 6.1.1 20160501).
I was a bit confused by the existence of `setUserData` but the absence of `getUserData`. It seems like a pointless member functions without a matching getter. I changed `setUserData` to not use the deprecated `Ogre::MoveableObject::SetUserAny`, and when I wanted to update the getter I noticed it wasn't there.
=> Fix compilation warnings

src/rviz/CMakeLists.txt
With strict ld flags, I get the following errors:
```
render_system.cpp: undefined reference to `XOpenDisplay'
render_system.cpp: undefined reference to `XCreateSimpleWindow'
```
There is a dependency on libX11 in ogre_helpers/render_system.cpp.
=> Add libX11 to librviz target_link_libraries

src/rviz/default_plugin/effort_display.h
In order to support compiling from source with GCC 6, this fix is also needed for indigo. Hence this PR to cherry-pick the fix from kinetic-devel (#1010) onto indigo-devel.
=> backport C++11 string literal fix to indigo

src/rviz/visualizer_app.cpp
I hate splash screens.
`setSplashPath` explains that the user can disable the splash screen by setting an empty path:
https://github.com/ros-visualization/rviz/blob/kinetic-devel/src/rviz/visualization_frame.h#L87-L91
But the user can't because if the splash screen path argument is empty, the function is not called:
https://github.com/ros-visualization/rviz/blob/kinetic-devel/src/rviz/visualizer_app.cpp#L277-L280
This PR fixes the behavior:
```
rosrun rviz rviz -s ""
```
=> Allow disabling RViz splash-screen

src/rviz/display_group.cpp, src/rviz/render_panel.cpp, src/rviz/visualization_manager.cpp
there were 2 non-fatal issues reported by valgrind:
1. RenderPanel's virtual method `sceneManagerDestroyed()` was called after destruction, because RenderPanel wasn't unregistered from SceneManager.
2. VisualizationManager's `default_visibility_bit_` was initialized from not-yet-initialized `visibility_bit_allocator_`
=> fix for two valgrind-reported issues

src/rviz/robot/robot.cpp
A couple of lines below the code accesses link->getChildJointNames() without
testing "link". The additional test guarantees the link is set before working
with it.
I noticed that when adding support to MoveIt to correctly initialize an empty
robot model after printing an error.
=> robot: check for root_link_ before use

CMakeLists.txt, package.xml, src/rviz/default_plugin/effort_display.cpp, src/rviz/default_plugin/effort_visual.cpp, src/rviz/robot/robot.cpp, src/rviz/robot/robot.h, src/rviz/robot/robot_joint.cpp, src/rviz/robot/robot_joint.h, src/rviz/robot/robot_link.cpp, src/rviz/robot/robot_link.h
urdfdom_headers uses C++ std::shared_ptr. As it exports it as custom
*SharedPtr type, we can use the to sty compatible.
This also adds a proper dependency for urdfdom-headers
=> Use urdf::*ShredPtr instead of boost::shared_ptr

src/rviz/default_plugin/pose_array_display.cpp, src/rviz/default_plugin/pose_array_display.h
This PR adds support for visualizing poses as 3D axes and arrows to the `PoseArrayDisplay` plugin, same as the `PoseDisplay` plugin. The previous 2D arrows in a single `Ogre::ManualObject` are still supported. That option will probably be more performant with very large numbers of poses.
However, the 3D axes are the only option that visualize the full pose, so it is still useful to have those as an option. The 3D arrows are there for consistency with the `PoseDisplay` plugin.
Should fix #869
=> Support 3D arrows and axes for visualizing PoseArrays.

src/rviz/default_plugin/view_controllers/orbit_view_controller.cpp, src/rviz/default_plugin/view_controllers/orbit_view_controller.h
Fixes #1020 
This PR adds two options:
- Setting the focal shape size.
- A zoom invariant mode so that the focal shape size does not change when zooming in/out.
~~The only problem with this PR is the initial shape size; I found no way of knowing the focal distance before the user interacts (zooms in or out) so the shape size at the start is a little bit arbitrary.~~
Fixed size:
---
Zoom invariant:
---
=> Tweak focal shape size marker depending on focal distance

src/rviz/displays_panel.cpp
This commit deletes the `AddDisplayDialog` object after use.
Copy operator of `QString` in `rviz::AddDisplayDialog::updateDisplay()` causes double free AFTER CLOSING THE DIALOG.
Since `AddDisplayDialog` object created in `DisplaysPanel::onNewDisplay` never deleted, local variable `topic_output` could be overwritten after leaving local scope.
This seems to have occurred especially in many-core (16-physical-core in my case) environments.
=> Fix double free in display dialog

src/rviz/tool.h, src/rviz/tool_manager.cpp, src/rviz/tool_manager.h
I added a QT signal to the base Tool class, which allows the tool to request deactivation programmatically. Upon creation of a Tool by the ToolManager, this signal is connected to a new closedTool() slot which deactivates the current tool and activates the default tool.
For example, I have a tool with an associated GUI window. When the user closes this window via the X button, the tool gets deactivated.
=> Added close() signal to Tool class

src/rviz/robot/robot.cpp
I noticed that @wjwwood added "needs forward port" to #1039.
If he'd just asked I would have provided the request directly...
=> robot: check for root_link_ before use (kinetic port of #1039)

src/rviz/properties/float_edit.cpp
Hi,
The float property line edit doesn't work on systems with a decimal comma separator locale. For example on Ubuntu 16.04, with ros kinetic and a french locale, it is impossible to enter a decimal value.
This pull requested fixes the problem.
Another possible fix would be to force the QDoubleValidator to use the "C" locale : 
> QDoubleValidator *validator = new QDoubleValidator(this);
> validator->setLocale(QLocale::c());
> setValidator(validator);
=> bugfix in float_edit for non-english locales 

src/rviz/default_plugin/path_display.cpp, src/rviz/default_plugin/path_display.h
Hi,
This PR is for adding pose markers (axes or arrow) to Path display.
I personally wanted this feature to visualize the planned path including the pose of each waypoint.
Please merge if anyone needs this and the patch is acceptable.
Thank you,
=> Add a feature to display pose markers(axes or arrow)

CMakeLists.txt, package.xml, src/rviz/default_plugin/effort_display.cpp, src/rviz/default_plugin/effort_visual.cpp, src/rviz/robot/robot.cpp, src/rviz/robot/robot.h, src/rviz/robot/robot_joint.cpp, src/rviz/robot/robot_joint.h, src/rviz/robot/robot_link.cpp, src/rviz/robot/robot_link.h
Reapplied #1044, using urdf::SharedPtr instead of explicit boost::shared_ptr.
Fixed compatibility issues with older `urdfdom 0.3`, by relying on https://github.com/ros/robot_model/pull/160.
=> urdfdom compatibility

src/rviz/default_plugin/path_display.cpp
=> Fixed duplicate property name for Path colors

src/rviz/ogre_helpers/mesh_shape.cpp, src/test/render_points_test.cpp, src/test/two_render_widgets.cpp
This PR adds a few `include` statements that are required to build with Ogre 1.10. In Ogre 1.10 a few number of classes are now only forward declared by the headers RViz used. I tried to find something in the Ogre changelog about it, but I couldn't. They are not new headers in 1.10 though, so there should be no backwards incompatibilities.
There is also a large number of deprecation warnings now. I may have a go at those later, but these changes are really required to build with Ogre 1.10.
=> Include missing headers for ogre 1.10.

src/rviz/default_plugin/markers/mesh_resource_marker.cpp
Fixes COLLADA mesh material colors as described in issue https://github.com/ros-visualization/rviz/issues/751. From the issue thread, it looks like this case has already been fixed by @wjwwood ([752](https://github.com/ros-visualization/rviz/pull/752)), but unfortunately it got unfixed by another PR ([893](https://github.com/ros-visualization/rviz/pull/893)).
- Tested locally with Collada file generated by Blender. Without the fix, this image would be plain white.
- Tested with example by @garaemon: https://github.com/garaemon/rviz_collada_marker
- The fix implemented here was originally proposed by @brindza
=> Visualization collada texture in marker fix

src/rviz/robot/robot_link.cpp, src/rviz/robot/robot_link.h
this is rewrited version of #812
we'll get 
with this urdf
```
<?xml version="1.0"?>
<robot name="hoge">
<link name="base_link">
<visual>
<geometry>
<cylinder length="4" radius="1"/>
</geometry>
<material name="black_metal">
<color rgba="0.1 0.1 0.1 1"/>
</material>
</visual>
<visual>
<geometry>
<cylinder length="2" radius="5"/>
</geometry>
<material name="gold">
<color rgba="1 0.549 0 1"/>
</material>
</visual>
</link>
</robot>
```
=> support multiple material for one link

src/rviz/ogre_helpers/render_system.cpp, src/rviz/ogre_helpers/render_system.h, src/rviz/ogre_helpers/render_widget.cpp, src/rviz/visualization_manager.cpp
On Apple retina displays, the render widget only occupies a quarter of the available screen estate due to the higher DPI resolution. This PR fixes the problem for the render display and the mouse events.
=> Correctly scale the render panel on high resolution displays

src/rviz/default_plugin/point_cloud2_display.cpp
Currently, a PointCloud2 display keeps showing the old point cloud if an empty point cloud message is published. I consider this a bug, since rviz still shows old data which is invalid in the meantime.
=> Update display if empty pointcloud2 is published

src/rviz/default_plugin/map_display.cpp, src/rviz/default_plugin/map_display.h
Addresses #1065. Wasn't sure what name to give the property in the display window. I'm open to suggestions if anyone has any!
=> Adding option to transform map based on header timestamp

src/rviz/panel_dock_widget.cpp, src/rviz/panel_dock_widget.h, src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h
This PR adds an option to enter fullscreen mode, hiding all interface elements and showing nothing but the rendered view. It makes rviz much nicer to use for showing information in demo setups.
I added the option under the `view_menu_` in code, but it turns out it's actually called "Panels" in the GUI. That might make it the wrong place for this option. Alternatively the menu could be renamed to view, or a new view menu could be added.
F11 also works, and is the only way other than restarting rviz to leave fullscreen mode. Might make sense to also use Escape for that?
One point of note: I'm using `setHideButtonVisibility(bool)` which is a public member of `VisualizationFrame`. I couldn't find anything actually calling the member, but if it is exposed to plugins they could potentially …
=> Add fullscreen option.

ogre_media/materials/glsl120/nogp/nogp.program
Fixes the issue posted [here](https://github.com/ros-visualization/rviz/issues/1049).
As mentioned, the install is non-standard (Ogre 1.10), which might explain why I also had to modify `mesh_shape.cpp` to include `OgreMesh.h`. I was getting a forward declaration build error for Ogre::Mesh.
Also, I have not tested the effects on the affected `nogp` processes, but a standard install allowed me to run rviz on El Capitan with no problems, including correct image rendering.
=> Nogp update

src/rviz/robot/robot_link.cpp
I believe this should fix the compiler errors of the latest rviz release on some platforms which were introduced in: https://github.com/ros-visualization/rviz/pull/1079
=> fix type error in newer versions of urdf

src/rviz/default_plugin/covariance_property.cpp, src/rviz/default_plugin/covariance_property.h, src/rviz/default_plugin/covariance_visual.cpp, src/rviz/default_plugin/covariance_visual.h, src/rviz/default_plugin/odometry_display.cpp, src/rviz/default_plugin/odometry_display.h, src/rviz/default_plugin/pose_with_covariance_display.cpp, src/rviz/default_plugin/pose_with_covariance_display.h
This PR adds the current state of the rviz_plugin_covariance to rviz.
=> Covariances updated

src/rviz/ogre_helpers/render_system.cpp, src/rviz/ogre_helpers/render_system.h, src/rviz/ogre_helpers/render_widget.cpp
This should fix #1100 
@Kukanani can you give this a try and see if it fixes it for you?
=> Fix render system

src/rviz/robot/robot_link.cpp
Two places in `robot_link.cpp` forgot to increment the static counter for creating unique material names. Since Ogre 1.10 this is not just a possible visual glitch but also an error resulting in an `Ogre::ItemIdentityException`:
```
terminate called after throwing an instance of 'Ogre::ItemIdentityException'
what():  ItemIdentityException: Resource with the name robot link color material 1 already exists. in ResourceManager::add at /build/ogre/src/ogre/OgreMain/src/OgreResourceManager.cpp (line 150)
```
This PR increments the counter, and RViz no longer crashes when attempting to visualize a robot.
=> Use unique material names for robot links.

src/rviz/ogre_helpers/render_system.cpp
Somehow, variable names got out of sync. Lines 370 and 371 refer to "parameters" but it is "params" everywhere else.
Thanks for the Retina fixes! Just tested on Sierra and they work great.
=> Update variable name

CMakeLists.txt, package.xml, src/rviz/default_plugin/effort_display.cpp, src/rviz/default_plugin/effort_visual.cpp, src/rviz/default_plugin/path_display.cpp, src/rviz/default_plugin/point_cloud2_display.cpp, src/rviz/ogre_helpers/render_system.cpp, src/rviz/ogre_helpers/render_system.h, src/rviz/ogre_helpers/render_widget.cpp, src/rviz/panel_dock_widget.cpp, src/rviz/panel_dock_widget.h, src/rviz/robot/robot.cpp, src/rviz/robot/robot.h, src/rviz/robot/robot_joint.cpp, src/rviz/robot/robot_joint.h, src/rviz/robot/robot_link.cpp, src/rviz/robot/robot_link.h, src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h, src/rviz/visualization_manager.cpp
In preparation for the next Indigo release (last jade release of rviz).
In this backport:
- Support later versions of urdfdom: https://github.com/ros-visualization/rviz/pull/1064
- Fix rendering of point cloud when empty point cloud is received: https://github.com/ros-visualization/rviz/pull/1073
- Fix scaling of render area on high resolution displays: https://github.com/ros-visualization/rviz/pull/1078
- Support multiple material names in urdf: https://github.com/ros-visualization/rviz/pull/1079
- Fix bug in path display which prevented saving path color in config files: https://github.com/ros-visualization/rviz/pull/1089
- Fix to urdf type being used: https://github.com/ros-visualization/rviz/pull/1098
- Fix for supporting multiple material names in urdf: …
=> indigo-devel backports from kinetic-devel (1.12.9)

src/rviz/visualization_frame.cpp
This fixes a known issue (#1116) where keyboard shortcuts to trigger menu actions do not work. 
The action has to be added to the parent frame as well as the menu itself. The Fullscreen action (F11) was already doing that correctly.
I also added a (pretty standard) keyboard shortcut for Save As.
=> Add keyboard shortcuts actions to VisualizationFrame directly

src/rviz/default_plugin/map_display.cpp
Hi all,
I've noticed that changes of resolution to an occupancy grid map are not correctly reflected in RViz. I've investigated the `map_display` plugin code and noticed that `createSwatches()` in `MapDisplay::showMap()` is only called when the width or height changes, but not the resolution. I therefore extended the `if(width != width_ || height != height_){ ...` accordingly. Note that changing resolutions are (still) correctly reflected in RViz' UI panel.
I've tested this in ROS Kinetic and it works like a charm. Would be great if you merge my PR upstream. Thank you!
=> map_display: don't ignore resolution changes in OccupancyGrid maps

src/rviz/config.h
Without this patch, qt4's moc fails for classes
that use rviz headers if boost is at version >= 1.64.
The error message looks like this:
```
Generating MOC source moc_trajectory_panel.cpp
/usr/include/boost/predef/language/stdc.h:52: Parse error at "defined"
AutoMoc: Error: moc process for moc_trajectory_panel.cpp failed:
/usr/include/boost/predef/language/stdc.h:52: Parse error at "defined"
```
=> add qt-moc safeguard in config.h

src/rviz/robot/robot_link.cpp
When loading meshes without a material defined, rviz crashes with error:
```
terminate called after throwing an instance of 'Ogre::ItemIdentityException'
what():  ItemIdentityException: Resource with the name RVIZ/ShadedRed0Robot already exists.
```
Seems like this was the intended purpose of adding the `static int count`.
=> Fix Ogre::ItemIdentityException when loading mesh without material

src/rviz/default_plugin/markers/mesh_resource_marker.cpp
This is a forward port of #1084 for Kinetic. I'm pretty sure I already forward ported it, but perhaps it my other forward/back porting I accidentally merged over this change in Kinetic. It appears to be intact on `indigo-devel`.
See also: https://github.com/ros-visualization/rviz/issues/1120
=> Visualization collada texture in marker fix (#1084)

src/rviz/default_plugin/view_controllers/fixed_orientation_ortho_view_controller.cpp, src/rviz/default_plugin/view_controllers/fps_view_controller.cpp, src/rviz/default_plugin/view_controllers/orbit_view_controller.cpp, src/rviz/view_controller.cpp, src/rviz/view_controller.h
It's common in certain domains (e.g., aerospace) to construct models and environments with a Z-down coordinate system (it's still right-handed). When visualizing data from such environments, rviz is difficult to use because its camera controls are designed to prefer the ROS-standard Z-up convention. In particular, when working with a Z-down robot model, it's impossible to get an "over-the-shoulder" view of the robot.
This PR adds an orbit view controller option to invert the Z axis to make it easier to work with Z-down environments. To minimize confusion, the option is hidden by the non-orbit based view controllers that don't support it.
=> Add option to invert Z axis for orbit-based view controllers

src/rviz/visualization_frame.cpp
Hi,
On Ubuntu 16.04 (with the kde desktop environment from the kde backports ppa), moving the camera makes the taskbar freeze for several minutes (while using 100% CPU).
This happens because : 
When the user does move/rotate the camera
-> the pitch/yaw/... properties are updated
-> setWindowModified( true ) is called to notify the qwidget some modifications are pending
-> in setWindowModified() Qt will update the title bar of the rviz window, to add the ' * '
The problem is that kde's task manager has a hard time processing "new window title" events at several hundred times per second, thus freezes.
This pull request fixes the issue on my system
=> Only update window title if necessary

CMakeLists.txt, src/rviz/CMakeLists.txt, src/rviz/default_plugin/robot_model_display.cpp
Since https://github.com/ros/pluginlib/pull/59 pluginlib doesnt find_package tinyXML anymore. So downstream packages using tinyxml have to find it themselves.
This builds and passes the tests locally but I didn't run prerelease jobs or run nany manual test for it.
Note @wjwwood & @dhood this will require a new lunar release
=> find tinyxml and link against it

src/rviz/default_plugin/point_cloud_common.cpp
After adding new points to the PointCloud, setRenderMode call regenerateAll which remove all points and add then again (to apply the new render mode). 
As the PointCloud is just created, it is empty. So calling setRenderMode before addPoints  avoid the regeneration and improve performance.
This is an easy performance improvement, there a lot a copying in this plugin that hurt perf, with patterns like allocating a lot of memory to throw it right away from each new incoming pointcloud (or depth_cloud). I might find some time to dig more deeply into it.
=> Avoid unnecessary addPoints in PointCloudCommon::update

src/rviz/robot/robot.h, src/rviz/robot/robot_joint.h, src/rviz/robot/robot_link.h
I needed this patch to compile the indigo-devel branch (or the latest released version [1.11.18](https://github.com/ros-visualization/rviz/tree/1.11.18)) successfully in Ubuntu Xenial with Boost 1.58 and Qt 4.8.7 for a custom build of `ros-indigo-desktop-full` from source:
```cpp
Generating moc_robot.cpp
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
AUTOGEN: error: process for /home/jenkins/workspace/ros-indigo-xenial/rviz/obj-x86_64-linux-gnu/src/rviz/moc_robot.cpp failed:
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
Generating moc_robot_joint.cpp
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
AUTOGEN: error: process for …
```
=> Fix moc error with Qt 4.8.7 and Boost 1.58 in xenial

src/rviz/default_plugin/markers/triangle_list_marker.cpp
=> Only tear down triangle list objects if they've been created 

plugin_description.xml, src/rviz/default_plugin/point_cloud_transformers.cpp, src/rviz/default_plugin/point_cloud_transformers.h
I need to overlay color point cloud on mono one.
For example, grasp point on sensor input.
=> MONO8 transformer for point cloud plugin

src/rviz/default_plugin/interactive_marker_display.cpp, src/rviz/default_plugin/map_display.cpp, src/rviz/default_plugin/marker_display.cpp, src/rviz/default_plugin/odometry_display.cpp, src/rviz/default_plugin/path_display.cpp, src/rviz/default_plugin/pose_array_display.cpp, src/rviz/default_plugin/pose_display.cpp, src/rviz/default_plugin/pose_with_covariance_display.cpp, src/rviz/validate_quaternions.h
Added checks for quaternions before passing them to OGRE to fix crashes due to unnormalized quaternions as described in #1142.
=> Added check for invalid quaternions.

src/rviz/default_plugin/interactive_marker_display.cpp, src/rviz/default_plugin/map_display.cpp, src/rviz/default_plugin/marker_display.cpp, src/rviz/default_plugin/odometry_display.cpp, src/rviz/default_plugin/path_display.cpp, src/rviz/default_plugin/pose_array_display.cpp, src/rviz/default_plugin/pose_display.cpp, src/rviz/default_plugin/pose_with_covariance_display.cpp, src/rviz/validate_quaternions.h
Since https://github.com/ros-visualization/rviz/pull/1180 fixes the only confirmed issue with invalid quaternions, don't reject them anymore.
Null quaternions will be set to identity by `FrameManager::transform` where appropriate. We do not output a warning for these because they are common in uninitialised ROS messages and are more likely indicative of users just being lazy than an error in the publisher.
Non-null, unnormalised quaternions will generate a warning, as it may be from an error in the code of the publisher (see https://github.com/ros-visualization/rviz/pull/1179#issuecomment-354910545). It would be most convenient for this warning to be displayed as a status in the GUI so it can be coupled with the specific offender. However, #1167 has revealed that there are many such cases …
=> Warn on unnormalised quaternions instead of rejecting them

src/rviz/visualizer_app.cpp
When running `rviz -d bla`, rviz would segfault as it tried to extract a substring of the display-config parameter without checking its size first.
=> check length of display-config parameter before extracting substring

src/rviz/default_plugin/CMakeLists.txt, src/rviz/default_plugin/interactive_markers/interactive_marker_control.cpp, src/rviz/default_plugin/marker_display.cpp, src/rviz/default_plugin/marker_utils.cpp, src/rviz/default_plugin/marker_utils.h
May I ask for a central `createMarker()` function to create an rviz Marker given a specific marker type?
This functionality was already coded twice in rviz itself and - as I need it in an external project now - I would go for another copy otherwise.
This PR provides the requested functionality to create markers based on the known marker types in `visualization_msgs::Marker` at the core location, which knows about all these types.
=> provide createMarker()

src/rviz/default_plugin/map_display.cpp
This fixes a [-Wmismatched-new-delete](https://clang.llvm.org/docs/DiagnosticsReference.html#wmismatched-new-delete) compiler warning with Apple LLVM version 9.0.0 (clang-900.0.39.2) in macOS Sierra:
```cpp
[ 77%] Building CXX object src/rviz/default_plugin/CMakeFiles/rviz_default_plugin.dir/map_display.cpp.o
/Users/vagrant/ros_kinetic_desktop_ws/src/rviz/src/rviz/default_plugin/map_display.cpp:213:3: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
delete pixels;
^
[]
/Users/vagrant/ros_kinetic_desktop_ws/src/rviz/src/rviz/default_plugin/map_display.cpp:183:27: note: allocated with 'new[]' here
unsigned char* pixels = new unsigned char[pixels_size];
^
```
According to the [C++ …
=> Fix compiler warning and potential heap corruption due to mismatched new/delete

CMakeLists.txt
Not sure why this wasn't being installed.
`Help` > `Show Help Panel` works now (without it gives "Help file '/opt/ros/kinetic/share/rviz/help/help.html' does not exist.")
=> Install help.html

src/rviz/default_plugin/camera_display.cpp
This should fix camera_display when using roi.
=> Taking roi in cameraInfo in consideration when using camera_display plugin

src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h
Fixes #1148 
Diff without trailing whitespace changes:
https://github.com/ros-visualization/rviz/compare/kinetic-devel...VictorLamoine:QTabWidget_elide?w=1
The new slot `onDockPanelChange` checks for every QTabBar there is in the main window and makes sure text is not elided inside it.
This slot is triggered
- When a config file is loaded
- When a panel is created
- When a panel is moved
=> Disable dock widget text eliding

src/rviz/default_plugin/point_cloud_common.h
Looks like it was missed in this pr or has since regressed: https://github.com/ros-visualization/rviz/pull/1217
=> change to use non-deprecated header

src/rviz/CMakeLists.txt, src/rviz/preferences.h, src/rviz/preferences_dialog.cpp, src/rviz/preferences_dialog.h, src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h
Redo of #1106 on behalf of @MasterEric , who wrote:
> For tutorials installed to a read-only location, it may be disorienting for the user to be prompted to save. For this reason, I created a preferences dialog window, with a boolean option for whether to Prompt Save on Exit, defaulting to true. These preferences are saved to any config .rviz files that are created.
=> Created a new Preferences window, and added PromptSaveOnExit option.

README.md
So that the badge reflects the state of kinetic-devel branch instead of the latest PR build
=> Show badge of devel job instead of PR job in readme

CMakeLists.txt, src/rviz/default_plugin/effort_display.cpp, src/rviz/default_plugin/markers/triangle_list_marker.cpp
Backports for:
- Only tear down triangle list objects if they've been created: https://github.com/ros-visualization/rviz/pull/1164
- Install help.html: https://github.com/ros-visualization/rviz/pull/1218
- Ensure robot model has been loaded before processing JointState msg: https://github.com/ros-visualization/rviz/pull/1229
=> Indigo backports from kinetic-devel

src/rviz/default_plugin/point_cloud_common.h
Backport of https://github.com/ros-visualization/rviz/pull/1231, followup of https://github.com/ros-visualization/rviz/pull/1217
=> change to use non-deprecated header (#1231)

CMakeLists.txt, package.xml, src/rviz/CMakeLists.txt, src/rviz/default_plugin/robot_model_display.cpp, src/rviz/display_factory.cpp, src/rviz/mesh_loader.cpp
This should also fix the last warnings for our `melodic-devel` branch, letting CI be green again.
Closes #1235
=> convert to tinyxml2 to avoid deprecated interfaces in urdf

src/rviz/default_plugin/wrench_display.cpp, src/rviz/default_plugin/wrench_display.h, src/rviz/default_plugin/wrench_visual.cpp, src/rviz/default_plugin/wrench_visual.h
The default behavior for wrench messages was to hide the visualization if the length of the vector was smaller than the width. This pull request adds a boolean property to enable/disable this feature as discussed in  #1081.
I also renamed the function `updateColorAndAlpha()` to `updateProperties()`. The name made no sense anymore (even before) because scale and width are also updated here. The new name clarifies that several properties are updated.
@v4hn
=> hiding small wrenches should be optional

src/rviz/render_panel.cpp, src/rviz/render_panel.h
currently all mouse events get forwarded to onRenderWindowMouseEvents,
there keyboard focus is requested (setFocus) unconditionally. This commit
adds a new property "focus_on_mouse_move_" that enables setting keyboard
focus on mouse move events. Setting focus on click or wheel is handled by
QObject::setFocusPolicy
Subclasses/Users of rvis::RenderPanel can disable either setting focus on
mouse move by using the boolean property and disable keyboard focus on click,
on wheel or totally via setFocusPolicy
=> add option to disable keyboard focus being set on mouse move

package.xml
Follow-up of https://github.com/ros-visualization/rviz/pull/1217
For users trying to build rviz with an outdated pluginlib version
=> add minimum required pluginlib version

src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h
When using a lot of tools, it's annoying that not all tools fit in the default toolbar. This PR adds an additional tool menu (next to the remove tool menu) for configuring the tool button style: http://doc.qt.io/archives/qt-4.8/qt.html#ToolButtonStyle-enum
=> feat: Configurable tool button style kinetic

src/rviz/default_plugin/depth_cloud_display.h
Use portable uint32_t from <cstdint> in depth_cloud_display.h for better cross-compiling.
=> [Windows][melodic] Use portable uint32_t from <cstdint> in depth_cloud_display.h

src/rviz/default_plugin/CMakeLists.txt
In CMake, `TARGET_FILE_NAME` returns `.so` on Linux but `.lib` on Windows. However, `.lib` is the extension for imported library, and `.dll` is the expected extension to return (for shared libraries).
Using `TARGET_LINKER_FILE_NAME` makes sure that it returns `.so` and `.dll` for both platforms.
=> [Windows][melodic] Use portable TARGET_LINKER_FILE_NAME to get shared lib name.

src/rviz/ogre_helpers/render_system.cpp
On native Windows environment (not MingGW or Cygwin), it doesn't have XLib, so conditionally compile the code like macOS.
=> [Windows][melodic] Disable XLib code path on Windows

src/rviz/mesh_loader.cpp
(This seems to me not a Windows-specific issue, so I chose directly to create a PR against `melodic-devel`.)
`MemoryResource` returns the buffer pointer and size but doesn't have the guarantee the buffer being null-terminated (which makes sense since `MemoryResource` could hold anything in binary format.)
However, `xmlDoc.Parse()` either requires a null-terminated string, or an explicit buffer size to read. Otherwise, when the parser reads the bytes beyond the actual buffer size, it will lead to unexpected behavior (In my observation, this issue will manifest as `XML_ERROR_PARSING_TEXT` error.) and a scale of 1.0 will be returned.
So, specify the buffer size when calling Parse() to make sure it only reads till the buffer end.
=> [melodic] Correct xmlDoc.Parse usage.

src/rviz/selection/forwards.h, src/rviz/selection/selection_manager.cpp
- Users are not able to interact with interactive markers when running this [tutorial](http://wiki.ros.org/rviz/Tutorials/Interactive%20Markers%3A%20Getting%20Started).
- Meanwhile, `Incompatible pixel format [10]` are printed in RViz verbose mode.
On Windows, PF_R8G8B8 could be returned by pixel_buffer in `selection_manager`:
https://github.com/ros-visualization/rviz/blob/26ffa641a8e325aa7ced426c543a4433b8077684/src/rviz/selection/selection_manager.cpp#L735
However, `colorToHandle()` doesn't support PF_R8G8B8, so it errors out with `handle=0`. Add the proper case to fix it.
BTW, on Windows, it does honor the pixel format passed at the below line:
https://github.com/ros-visualization/rviz/blob/26ffa641a8e325aa7ced426c543a4433b8077684/src/rviz/selection/selection_manager.cpp#L396
After …
=> [Windows][melodic] Add Ogre::PF_R8G8B8 support in selection_manager

CMakeLists.txt, src/rviz/default_plugin/effort_display.h
... and thus the need for boost::signals(1), which was removed from boost in version 1.69.
Resolves #1343.
=> remove support for tf < 1.11.3

src/rviz/visualization_frame.h
... to allow saving of programmatically created panels.
Otherwise, panels can only be added via addPane(), which doesn't add them to `custom_panels_`.
However, [only panels in `custom_panels_` are actually saved](https://github.com/ros-visualization/rviz/blob/melodic-devel/src/rviz/visualization_frame.cpp#L931-L934).
Would be great to backport this to Kinetic too.
=> expose VisualizationFrame::addPanelByName()

src/rviz/default_plugin/robot_model_display.cpp
I observed some spurious (error) status msgs in RobotModelDisplay when loading rviz. In my situation I had a (left-over) `robot_description`, and another robot description (with a different name) on the parameter server. When loading, the RobotModelDisplay first loads the default `robot_description`, missing all the link transforms, then loads the correct robot description. The error msgs however remain.
Hence, before loading a new model, all status messages should be cleared.
=> RobotModelDisplay: clear statuses when (re)loading a model

.github/PULL_REQUEST_TEMPLATE.md
Some context: ros-planning/moveit#1131 and ros-planning/moveit#1027.
Adds a PR template (inspired by the one from MoveIt) with the express request to review other outstanding PRs.
In addition it points to the PR review guidelines both by @wjwwood on the wiki here at `ros-visualization/rviz` and the general review guidelines as being prototyped over at [rosin-project/ros_code_review_guide](https://github.com/rosin-project/ros_code_review_guide).
This is part of the trial started by the members of the software quality working group trying to get more people involved in maintainership and increase community participation in these processes.
=> Add PR template (SQWG trial)

src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h
=> feat: Configurable tool button style melodic

src/test/connect_test.cpp
Use c++11 <chrono> API to replace gettimeofday for better code portability.
=> [Windows][melodic] Use c++11 chrono to replace gettimeofday.

src/rviz/panel_dock_widget.cpp
Sometimes, after RViz starts up, some panels are not showing, even when I toggle through `menu > panels > xyz`. On Windows, the repro rate is high, like once out of 5 ~ 10 runs. On Ubuntu, we also observe the same symptom (but with a much lower reproduce rate).
The workaround is to enter\exit fullscreen to refresh the visibility states.
This is also reported on https://answers.ros.org/question/315664/ros-not-running-well-on-windows-10/.
After live debugging, I noticed sometimes `forced_hidden_` are not zero at start up. And it turned out `forced_hidden_` was not zero-initialized in constructor and it could be anything left from the memory, so it messed up with the later visibility logic.
The solution is to simply initialize it.
=> [melodic] RViz panels don't always show at startup

src/rviz/CMakeLists.txt
Replace the hard-coded target names with ${ASSIMP_LIBRARIES} and ${NEW_YAMLCPP_LIBRARIES} for better portability.
=> [Windows][melodic] Use ${ASSIMP_LIBRARIES} in CMakeLists.txt for better portability

src/rviz/default_plugin/effort_display.cpp
Moves all joint information into the **Joints** category.
=> Fixed joint display hierarchy in EffortDisplay

src/rviz/ogre_helpers/render_system.cpp
Replace assert with warning, fallback and error so that when in release mode, librviz does not segfault with a misconfigured DISPLAY env.
In our use of librviz, RenderSystem::setupDummyWindowId() was segfaulting since display was not set correctly. This will provide warnings, fallback and a useful error in such cases.
=> Replace display error assert with warning, fallback and error 

src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h
The fullscreen code does not properly keep track of the toolbar visibility state. This leads to the following undesired behaviour:
- Pressing esc without ever having entered fullscreen may hides the toolbar because toolbar_visible_ is never set.
- Pressing esc after having entered fullscreen previously sets the toolbar visibility to what it was the last time fullscreen was entered.
By only calling setFullScreen(false) after we really were in fullscreen mode, we guarantee that toolbar_visible_ is valid and don't mess with the toolbar visibility otherwise.
=> Don't hide the toolbar when pressing esc

help/help.html, src/rviz/display.cpp, src/rviz/failed_display.cpp, src/rviz/panel_dock_widget.cpp, src/rviz/properties/property.cpp, src/rviz/properties/property_tree_with_help.cpp, src/rviz/properties/status_property.cpp, src/rviz/properties/status_property.h, src/rviz/view_controller.cpp
This improves readability when using dark or other themes in RViz.
There are some other colors that might be improved but this fixes the main issues I have seen.
---
Does someone know where the color is set for the status tree and similar entries?
=> Improve color support for themes

CMakeLists.txt
I was attempting the package rviz in a snap and had difficulty because of OGRE_PLUGIN_PATH.  The OGRE_PLUGIN_PATH would take a path pointing to a build directory from the package config.  This allows OGRE_PLUGIN_PATH to be specified as a cmake arg if the plugin path is known to be different on the system rviz is installed from the one it is built on.
=> OGRE_PLUGIN_PATH definable at build time

src/rviz/default_plugin/tools/initial_pose_tool.cpp, src/rviz/default_plugin/tools/initial_pose_tool.h
Currently the initial pose tool has a hardcoded covariance matrix. Sometimes it is useful to send an initial pose with a low covariance. This PR adds properties to the initial pose tool that allows specifying the main elements of the covariance matrix.
=> Add properties for the covariance of the initial pose tool

src/rviz/mesh_loader.cpp
Fixed #1352. ErrorStr() was only introduced in tinyxml2 6.x, and is not yet available on Debian Stretch.
This leaves us with a less detailed error string.
=> replace tinyxml2  ErrorStr() -> ErrorName()

src/test/send_images.cpp
This change is fixing the run_tests build breaks when `catkin_make run_tests` on Windows. `random` doesn't exist on Windows so switch to C++ `<random>` library for better portability.
=> [Windows][melodic] Fix the run_tests build breaks on Windows.

src/python_bindings/sip/CMakeLists.txt
This is a goofy one, but the "binary dir" specified in `build_sip_binding` function is not a place to put built binaries, it's a place to put generated source, object files, etc. These don't belong in the develspace, they belong in the build space. Removing the line causes it to fall back to just using `PROJECT_BINARY_DIR`, see:
https://github.com/ros-visualization/python_qt_binding/blob/0.3.3/cmake/sip_helper.cmake#L196-L198
In case there's any doubt, here's what it places in that location, in a `sip/rviz_sip` subdirectory:
```
Makefile                                 siplibrviz_siprvizPanelDockWidget.o
pyqtscripting.sbf                        siplibrviz_siprvizProperty.cpp
sipAPIlibrviz_sip.h                      siplibrviz_siprvizProperty.o
siplibrviz_sipcmodule.cpp …
```
=> Move sip bindings build directory into the build space.

src/rviz/default_plugin/axes_display.cpp, src/rviz/default_plugin/axes_display.h, src/rviz/default_plugin/tf_display.cpp, src/rviz/default_plugin/tf_display.h, src/rviz/ogre_helpers/axes.cpp, src/rviz/ogre_helpers/axes.h
This adds a property named alpha to the Axes and TF displays that
changes the alpha channel value of the axes colors.
An updateAlpha method is added to Axes so that TF display can easily
change the default alpha value of the axes.
The default axes colors in the Axes object are changed to be fields
instead of static objects so that different axes objects can have
different alpha values.
It may be useful to make partially transparent axes for visualization purposes.
I am happy to make any requested changes.
=> Add ability to set alpha channel value of Axes and TF displays

src/rviz/default_plugin/view_controllers/orbit_view_controller.cpp, src/rviz/default_plugin/view_controllers/orbit_view_controller.h
This change adds a Property to the Orbit camera to change the field of view.
I found this change useful for visualization as it makes rviz more configurable.
I can also add this to the other cameras if this will be merged in / is desirable.
=> Add ability to set Orbit camera field of view

src/rviz/visualization_frame.cpp
Fixes #1369.
This fix does not revert dock text eliding disabling as introduced in #1168 for Qt4.
Tested with Qt4 v4.8.7.
=> Fix compilation with Qt4 (#1369)

src/rviz/ogre_helpers/movable_text.cpp
MovableText: Consider full `mGlobalTranslation` vector and not only y-component. Fixes #1355.
=> MovableText: consider full mGlobalTranslation vector

src/rviz/image/ros_image_texture.cpp
While working on the integration between Ignition and ROS (https://github.com/osrf/ros1_ign_bridge/pull/15), we ran into an issue where depth images were not properly displayed on RViz.
This PR makes sure that [REP 117](http://www.ros.org/reps/rep-0117.html) is followed, and values like NaN and +-inf are ignored when normalizing depth images.
Without this PR, images containing NaN / Inf display completely black when "Normalize" is checked, because those values are used to calculate the normalization boundaries. With this PR, depth images coming from [ign-sensors](https://bitbucket.org/ignitionrobotics/ign-sensors) and relayed through the [ros1_ign_bridge](https://github.com/osrf/ros1_ign_bridge) display correctly, as shown below:
=> Ignore special conditions when normalizing image

src/rviz/ogre_helpers/movable_text.cpp
As pointed out in https://github.com/ros-visualization/interactive_markers/issues/40, rviz doesn't support non-ASCII chars in rendered text. This was due to two shortcomings:
1. The std::string, which is utf8-encoded on Linux nowadays, wasn't interpreted as an utf8-encoded string, but as an ASCII string.
2. To render non-ASCII chars, the font needs to load corresponding textures. By default, it looks like only 0-127 are loaded, which makes sense to limit memory usage. 
I extended the range arbitrarily to 0-999, solving the mentioned issue:
However, that's not an optimal solution at all, because it loads many textures that aren't probably used by most applications. On the other hand, still lots of chars are missing.
What would be needed, is a mechanism to explicitly specify the required …
=> Enable non-ascii chars for MovableText

src/rviz/default_plugin/view_controllers/orbit_view_controller.cpp
This allows to zoom more on tiny objects in RViz. The user must lower the near clipping distance in order to zoom a lot.
=> Allow to zoom more in orbit view controllers

src/rviz/robot/robot_link.cpp
Fixes an issue introduced in #1294 (e906f82eb2ef04e63dea03f834ae722f144bc712):
Materials of Collada mesh models need to be cloned for each instance of a robot link.
Fixes #1385. @simonschmeisser, could you please verify?
=> Fix opacity of Collada meshes

src/rviz/default_plugin/marker_array_display.cpp, src/rviz/default_plugin/marker_array_display.h
Using a proper cast, g++ can correctly resolve the template type without requiring an extra helper function.
=> Remove extra wrapper MarkerArrayDisplay::handleMarkerArray

src/rviz/default_plugin/markers/shape_marker.cpp, src/rviz/validate_floats.h
Fix segfaults due to invalid marker messages.
=> Fix marker handling

src/rviz/default_plugin/marker_display.cpp, src/rviz/default_plugin/marker_utils.cpp, src/rviz/default_plugin/marker_utils.h, src/rviz/default_plugin/markers/arrow_marker.cpp, src/rviz/default_plugin/markers/line_list_marker.cpp, src/rviz/default_plugin/markers/points_marker.cpp, src/rviz/default_plugin/markers/shape_marker.cpp, src/rviz/default_plugin/markers/text_view_facing_marker.cpp, src/rviz/default_plugin/markers/triangle_list_marker.cpp
Using rviz Markers for debugging is often very useful, but sometimes the developer makes mistakes when filling in the fields of the marker.
In some cases the resulting markers are not visible or not displayed as intended.
In a few cases this lead to long debugging sessions when the actual problem was the visualization...
Until now there was little and unorganized debug output from rviz to assist the developer in some of these cases.
I have implemented a systematic check of all marker types as well as marker arrays
as described [here](http://wiki.ros.org/rviz/DisplayTypes/Marker) and implemented in the Display.
During testing I found some other bugs as well:
- `TEXT_VIEW_FACING` Markers with an empty text cause rviz to segfault.
- `TEXT_VIEW_FACING` Markers with text that consists …
=> systematic check of incoming markers

src/rviz/default_plugin/robot_model_display.cpp
`urdf::Model::initXml()` serializes the XML document to a string and reparses the XML later on.
Using `urdf::Model::initString()` this is avoided.
=> avoid double parsing in urdf::Model::initXml()

src/rviz/image/image_display_base.cpp
Fixes #1372. As https://github.com/ros/geometry2/pull/402 isn't released yet, I'm going to merge this quick fix here. Thanks to @hexonxons, who analyzed the bug in detail in #1393 and originally proposed a solution.
=> Fix segfault in Camera plugin

src/rviz/ogre_helpers/render_widget.cpp, src/rviz/ogre_helpers/render_widget.h
=> Resize RenderWidget properly when using different DPI scaling.

src/rviz/failed_display.cpp, src/rviz/failed_display.h
Overload `FailedDisplay::save` for properly overriding `Display::save` without breaking ABI.
Fix #1390
=> Overload FailedDisplay::save for proper override

src/rviz/default_plugin/map_display.cpp
Memory allocated by `make*Palette()` was not freed by anyone.
It is now allocated with Ogre's `OGRE_ALLOC_T` to be freed directly by `MemoryDataStream`.
Fix #1391
=> Properly free allocated memory

src/rviz/default_plugin/tf_display.cpp, src/rviz/default_plugin/tf_display.h
This PR simplifies `TFDisplay::deleteFrame()`, avoiding an extra lookup by frame name.
To fix the leak, free FrameInfo pointers by calling clear() in the destructor.
=> TFDisplay: simplify + fix memory leak

plugin_description.xml, src/rviz/default_plugin/CMakeLists.txt, src/rviz/default_plugin/view_controllers/frame_view_controller.cpp, src/rviz/default_plugin/view_controllers/frame_view_controller.h, src/test/cycling_frame.py
This is an alternative, much simpler implementation of #1403 drawing on the existing FPS view controller. If required, we could add a `BoolProperty` to lock the camera, i.e. disable mouse interaction as in #1403.
=> Frame-Aligned View Controller

src/rviz/default_plugin/camera_display.cpp, src/rviz/display.cpp, src/rviz/display.h, src/rviz/display_group.cpp, src/rviz/image/image_display_base.cpp, src/rviz/properties/property.cpp
This PR fixes several, partially long-standing, issues with Camera and Image display. See individual commit messages for details.
Fixes #940 
Fixes #1368 
Unfortunately, the current, "clean" implementation requires an ABI change.
But I added an ABI compatible solution, using a global map to store the new member instead.
=> Fix several issues with Camera and Image display

src/rviz/default_plugin/point_cloud_common.cpp
Address #1301. @christian-rauch, can you please test and review?
=> PointCloud display: fix memory leak in case of constant /clock

src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h, src/rviz/visualizer_app.cpp
=> Improve cmdline parsing and add --fullscreen option

src/rviz/default_plugin/marker_utils.cpp
Fixup to #1275 .
`std::lower_bound` was used to find the correct insertion position, which might be
somewhere within the vector. Thus, the check for MarkerID repetitions has to
perform the additional equality check.
Relevant for https://github.com/ros-visualization/rviz/issues/1414
=> Correctly detect repeated marker occurrences

src/rviz/default_plugin/markers/text_view_facing_marker.cpp
this fixes a regression/crash introduced in #1275 and discussed in #1414 that occurred when adding an empty text marker
=> fix crash on empty text in Interactive Marker

src/rviz/visualization_frame.cpp, src/rviz/visualization_manager.cpp, src/rviz/visualization_manager.h
Address #1257.
QShortCut was catched ESC key press before it could be passed to the tools.
=> ESC must not be catched by QShortcut

src/rviz/default_plugin/interactive_markers/interactive_marker.cpp, src/rviz/default_plugin/marker_utils.cpp, src/rviz/default_plugin/marker_utils.h, src/rviz/mesh_loader.cpp
This fixes some more issues of #1275:
- invalid quaternion: issue warning only
- triangle list accepts points.size()/3 colors as well (face colors)
- don't create (empty) text marker for interactive marker control with empty description 
(to avoid warning)
as well as #1365:
- use default material for .stl meshes
@v4hn and @simonschmeisser, could you please have a look?
=> Fixes for #1275 and #1365

src/rviz/render_panel.cpp, src/rviz/render_panel.h
This addresses #1175 
enable mouse tracking for render_panel
when mouseTracking is enabled for a QWidget it will get mouseMoveEvents even though no mouse button is pressed. This behavior was faked in rviz with a 30Hz timer.
This is currently preserving API/ABI but could just as well be non preserving and go to noetic only. I did not observe any positive or negative impact from this change, just cleaner code (eventually).
=> Mouse move

src/rviz/default_plugin/marker_display.cpp, src/rviz/image/image_display_base.cpp, src/test/marker_test.cpp
Fixes #1135. Obviously, when increasing the TF filter's queue size, we also need to adapt the subscriber's queue size, i.e. re-subscribe. Otherwise, we cannot even receive enough messages.
=> Adapt subscriber size with TF queue size

src/rviz/default_plugin/effort_display.h, src/rviz/default_plugin/fluid_pressure_display.cpp, src/rviz/default_plugin/fluid_pressure_display.h, src/rviz/default_plugin/illuminance_display.cpp, src/rviz/default_plugin/illuminance_display.h, src/rviz/default_plugin/laser_scan_display.cpp, src/rviz/default_plugin/laser_scan_display.h, src/rviz/default_plugin/point_cloud2_display.cpp, src/rviz/default_plugin/point_cloud2_display.h, src/rviz/default_plugin/point_cloud_display.cpp, src/rviz/default_plugin/point_cloud_display.h, src/rviz/default_plugin/range_display.cpp, src/rviz/default_plugin/range_display.h, src/rviz/default_plugin/relative_humidity_display.cpp, src/rviz/default_plugin/relative_humidity_display.h, src/rviz/default_plugin/temperature_display.cpp, src/rviz/default_plugin/temperature_display.h, src/rviz/message_filter_display.h
This is a replacement for #1113, addressing the comments listed there.
Also, it removes the now redundant `queue_size_property_` members in derived classes.
As this changes ABI, this PR targets Noetic only.
=> MessageFilterDisplay: add queue-size property

src/rviz/default_plugin/camera_display.cpp, src/rviz/default_plugin/camera_display.h, src/rviz/default_plugin/image_display.cpp, src/rviz/image/image_display_base.cpp, src/rviz/image/image_display_base.h, src/rviz/image/ros_image_texture.cpp, src/test/send_images.cpp
Currently, image displays report "no image received" - also in case images were received but had an unknown image frame. This PR adds a corresponding failure handling for TF frames.
However, for `ImageDisplay` an issue remains with `CameraInfo`: If the camera info is published latched, rviz only receives a single message (either success or failure depending on the frame status). If rviz' fixed frame changes (which probably changes the frame status of the camera as well), this change is not noticed anymore, because updates can only happen when a new TF message is received.
@wjwwood, hence my question: Should we latched CameraInfo messages be supported?
If so, we would need to memorize the latest received message in any case and validate its frame "manually" as soon as the fixed frame …
=> ImageDisplay: report frame issues

src/rviz/default_plugin/markers/line_strip_marker.cpp
=> LineStripMarker: ignore invalid points

src/rviz/CMakeLists.txt
This fixes the issue : 
```
ld: library not found for -lyaml-cpp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````
pkg config **succeeds** in finding yaml but linker fails on macOS (tested on catalina)
Now on newer version of yamlcpp, the cmake config is installed.
=> fix yaml-cpp not found on macOS (catalina)

src/rviz/mesh_loader.cpp
Fixes #1451. Some mesh exporters generate zero normals, which results in black visualizations.
Assimp's postprocess option [FindInvalidData](http://assimp.sourceforge.net/lib_html/postprocess_8h.html#a64795260b95f5a4b3f3dc1be4f52e410a42a93fc16a7a3b6df509bab503945421) allows to find and remove this invalid data. Subsequently the data is correctly re-generated by another assimp post-processor.
=> assimp importer: repair invalid normals

src/rviz/default_plugin/tools/goal_tool.cpp, src/rviz/default_plugin/tools/initial_pose_tool.cpp, src/rviz/default_plugin/tools/point_tool.cpp
Fix #1466: An invalid ros topic name caused rviz to crash due to the uncaught exception.
=> Catch exceptions when creating publishers in tools

CMakeLists.txt, src/rviz/properties/property_tree_widget.cpp, src/rviz/properties/property_tree_widget.h
Current behavior without this patch:
- Open RViz with any display added
- click on the right column in the display view, in the same row as the checkbox to enable/disable the display
=> pressing spacebar can toggle the checkbox
- click on the left column of the same row (the name of the display)
=> pressing spacebar has no effect
Additionally, a visible indicator of the current focus (not the current selection)
highlights the corresponding cell.
This patch modifies selection requests to always focus the right column (if available)
and achieve the first behavior consistently.
This allows to go through a long list of displays by keyboard and toggle them with spacebar.
=> always forward keystrokes in display view to property editor

package.xml
this removes the runtime dependency on libogre-dev and therefore simplifies working with multiple ogre versions installed (once they make it into Debian/Ubuntu ...). It also reduces installation size by a few kb
=> switch libogre-dev to build_depend

CMakeLists.txt, setup.py
-  Use setuptools instead of distutils 
Since ros/catkin#1048 catkin prefers to use setuptools instead of distutils. The package.xml doesn't need to include python3-setuptools because [catkin exports that dependency](https://github.com/ros/catkin/blob/86439ec5d2010d5c47c30b815aa97e525037930f/package.xml#L32) for the convenience of all downstream python packages.
-  Bump CMake version to avoid CMP0048
This bumps the minimum CMake version to 3.0.2, which is the [minimum supported by ROS Kinetic](https://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021) and new enough to default to the NEW behavior of [CMP0048](https://cmake.org/cmake/help/v3.0/policy/CMP0048.html). This avoids a CMake warning when building and testing this package in Debian Buster and Ubuntu Focal.
=> noetic release

src/rviz/CMakeLists.txt
Added missing cmake command to include yaml-cpp include directory. My source build requires this include to complete correctly with yaml-cpp 0.6.2.
None apply
=> fix: + include yaml cpp include directory

package.xml
This is a fixup of #1482 that unfortunately had to be reverted, it now also sets `build_export_depend`
Should ideally also be backported to melodic-devel
side-note: ogre-1.12.4 is now in Debian sid and there is still hope and an open request to get it into Ubuntu 20.04
=> Build depends

CMakeLists.txt
This pull request is to conditionally guard GCC\Clang-specific flags to avoid MSVC build breaks.
=> [noetic] Use GCC\Clang-specific flags when needed.

src/rviz/default_plugin/tools/measure_tool.cpp
Otherwise the line will hang around virtually forever.
=> MeasureTool: hide measure line when deactivating the tool

src/rviz/properties/property_tree_widget.cpp
This seems to be a corner-case one might actually call a bug in qt5.
the `setSelectionModel(new PropertySelectionModel(nullptr))` call
complains that the SelectionModel and the PropertyTreeView use different
models, although both are set to nullptr in user code.
Qt actually sets the model of QAbstractItemView to
the dummy `QAbstractItemModelPrivate::staticEmptyModel`, but the
SelectionModel is actually initialized with `nullptr`.
=> PropertyTree: set custom SelectionModel only with valid model

src/rviz/selection/selection_manager.cpp
I think the conversion to float is too lossy and thus selection of interactive marker arrows didn't work for me (I ended up in the size == 3 case).
=> fix selection of interactive markers

CMakeLists.txt, src/rviz/env_config.cpp.in
* assimp >= 5.0 no longer defines `ASSIMP_LIBRARIES`. A backward-compatible logic is added to link against assimp.
* Use cmake config files to locate OGRE by default and fallback to pkg-config if needed.
=> More portable assimp and OGRE discovery logic

src/rviz/properties/combo_box.cpp, src/rviz/properties/combo_box.h, src/rviz/properties/editable_enum_property.cpp, src/rviz/properties/splitter_handle.cpp
Follow up on #1545: The original fix missed some size updates. Thus, added QEvent::Show in SplitterHandle's event filter.
Also, combobox editors, created by enum properties need to be limited in width. To show the full enum texts in the drop down, this one might be wider.
=> PropertyWidget: Limit comboboxes to column width

src/rviz/ogre_helpers/render_system.cpp, src/rviz/properties/combo_box.cpp, src/rviz/properties/combo_box.h, src/rviz/properties/editable_enum_property.cpp, src/rviz/properties/splitter_handle.cpp
Fixes #1508. There seems to be an issue with GLSL 1.5 material scripts on Mesa-based systems.
=> Enforce GLSL 1.4 on Mesa systems

src/rviz/message_filter_display.h
This is a backport of https://github.com/ros2/rviz/pull/620 to resolve race conditions arising from processing messages from `TFMessageFilter` in non-gui threads. Fixes #1456.
=> MessageFilterDisplay: process messages synchronously

src/rviz/default_plugin/screw_display.h, src/rviz/default_plugin/screw_visual.h, src/rviz/default_plugin/wrench_visual.h
The recent commit https://github.com/ros-visualization/rviz/commit/dd1779e78dbb1468fdb11968632fafd5e7a272f2 broke compilation on Windows. This PR fixes this issue.
Compiler error without this patch:
```
%SRC_DIR%\ros-noetic-rviz\src\work\src\rviz\default_plugin\screw_display.cpp(87): error C2491: 'rviz::ScrewDisplay<MessageType>::ScrewDisplay': definition of dllimport function not allowed
%SRC_DIR%\ros-noetic-rviz\src\work\src\rviz\default_plugin\screw_display.cpp(95): error C2491: 'rviz::ScrewDisplay<MessageType>::onInitialize': definition of dllimport function not allowed
%SRC_DIR%\ros-noetic-rviz\src\work\src\rviz\default_plugin\screw_display.cpp(103): error C2491: 'rviz::ScrewDisplay<MessageType>::reset': definition of dllimport function not allowed …
```
=> Fix Windows compilation

src/rviz/tool.cpp, src/rviz/tool.h, src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h
With this PR the tool parameters will be available when `onInitialize` is called. One can use this feature to solve #1138 by adding
an `rviz::StringProperty`, e.g. named `Tool Name`, and then use its value to rename the tool in `onInitialize`.
=> [tool] load parameters before initializing

src/rviz/default_plugin/marker_utils.cpp
The interactive_markers package auto-completes scales to 1.0 if they are zero.
Hence, we should simply ignore those values. This partially reverts #1275.
=> Remove warnings about ignored marker scale

src/rviz/default_plugin/point_display.cpp
This PR fixes the following problem:
Currently the PointStamped display does not show added points as long as the circular buffer is filled once fully. This problem is most of the times not noticed if the history size is quite short or the topic is updated very fast. But if you have a topic with a slow rate and a long history it can take some time to fill the buffer. 
The solution is to set the radius before calling the `setMessage` function of `PointStampedVisual` as this function uses the radius to set the size of the underlying `Shape`.
=> set radius first for points displayed by PointStamped display

src/rviz/ogre_helpers/render_system.cpp
Mesa-based rendering issues showed up e.g. on AMD GPU as well. The new approach should handle any Mesa 20-based system.
Fixes #1584.
=> Enforce GLSL 1.4 on more Mesa systems (#1559)

src/rviz/ogre_helpers/render_system.cpp
This enables the Mesa workaround for Mesa 21.x, too (and all future Mesa 2?.x versions).
My system reports:
```
GL_RENDERER   = AMD RENOIR (DRM 3.40.0, 5.10.24-051024-generic, LLVM 11.0.1)
GL_VERSION    = 4.6 (Compatibility Profile) Mesa 21.0.0 - kisak-mesa PPA
GL_VENDOR     = AMD
```
The fix merged in #1588 is limited to Mesa 20.x only, but the problems it works around are present in 21.x, too.
=> Enable Mesa workaround also on Mesa 21

src/rviz/displays_panel.cpp, src/rviz/properties/color_editor.cpp, src/rviz/visualization_frame.cpp, src/rviz/visualizer_app.cpp, src/test/new_display_dialog_test.cpp
Create dialog objects on stack where possible. Otherwise use unique_ptr.
Fixes #1601.
=> Fix memory leaks in dialog handling

src/rviz/properties/color_editor.cpp
=> ColorEditor: maintain edited text + cursor pos

src/rviz/properties/line_edit_with_button.cpp, src/rviz/properties/line_edit_with_button.h
This function isn't used across the source of rviz. Usage was removed in f194580fb148830aad69fdaa77a3294319371603 back in 2012.
=> Remove unused LineEditWithButton::simulateReturnPressed()

.clang-format, .clang-tidy, .github/workflows/prerelease.yml
- enable full (and slow) clang-tidy check via manual workflow triggering only
- make CLANG_TIDY non-pendantic (there are too many open issues)
- add prerelease workflow
- auto-format .clang-format
- drop caching of target_ws and docker image
- the docker image continuously accumulates layers (comprising environment at least)
- caching the target_ws missed to rebuild sometimes
=> Fixup github actions

src/rviz/displays_panel.cpp, src/rviz/loading_dialog.cpp, src/rviz/ogre_helpers/render_widget.cpp, src/rviz/visualization_frame.cpp
Both dialogs didn't correctly update their content during the long-running functions they were used in.
Resolves https://github.com/ros-visualization/rviz/issues/1612#issuecomment-820416989.
=> Fix usage of QProgressDialog / LoadingDialog

src/rviz/ogre_helpers/render_widget.cpp
Several users in the RoboStack project reported that rviz scaling didn't work for high-dpi screens: https://github.com/RoboStack/ros-noetic/issues/102
We use Ogre 1.10 in RoboStack. After applying https://github.com/RoboStack/ros-noetic/commit/057e616d4d03c4dc23567dd1b82d2add4b7de2d0 it is now working fine.
Therefore, I think the selector for the Ogre version was wrong and this PR fixes it.
=> Fix resizeEvent for OGRE==1.10

src/rviz/default_plugin/robot_model_display.cpp, src/rviz/properties/property_tree_with_help.cpp, src/rviz/robot/robot_link.cpp, src/rviz/robot/robot_link.h
This PR implements https://github.com/ros-visualization/rviz/pull/1597#issuecomment-802670884 and fixes #1589.
@simonschmeisser, please have a look. I decided to summarize all mesh loading issues as part of the URDF field.
As you noticed in #1597, TF updates to the link status will overwrite previous errors and introducing a new status field, I didn't like so much.
=> Robot: Report mesh loading issues

src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h
This adds a new signal `VisualizationFrame::displayConfigFileChanged` and defines a name for the quit action to allow fixing some issues in [`rqt_rviz`](https://github.com/ros-visualization/rqt_rviz).
=> Extending API for rqt_rviz

src/rviz/default_plugin/depth_cloud_display.cpp, src/rviz/default_plugin/fluid_pressure_display.cpp, src/rviz/default_plugin/illuminance_display.cpp, src/rviz/default_plugin/laser_scan_display.cpp, src/rviz/default_plugin/point_cloud2_display.cpp, src/rviz/default_plugin/point_cloud_common.cpp, src/rviz/default_plugin/point_cloud_common.h, src/rviz/default_plugin/point_cloud_display.cpp, src/rviz/default_plugin/relative_humidity_display.cpp, src/rviz/default_plugin/temperature_display.cpp, src/rviz/displays_panel.cpp, src/rviz/visualization_manager.cpp
VisualizationManager uses `[start|stop]Update()` to pause ROS updates during dialog box interaction (#631).
However, asynchronous updates via `threaded_queue_` were still performed, leading to a memory leak (#1621),
because messages were partially processed by the thread (i.e. kept in memory), but not finally processed
(and cleaned up) by the synchronous `Display::update()` call.
Pausing threaded processing too resolves that issue.
Fixes #1621. Fixes #868.
@simonschmeisser: Do you see any issue pausing asynchronous message processing too while displaying dialogs?
=> Pause asynchronous ROS updates with synchronous ones

src/rviz/displays_panel.cpp, src/rviz/visualization_frame.cpp, src/rviz/visualization_manager.cpp
Partially reverts #631. Fixes #1606.
=> Continue processing messages while displaying dialogues

src/rviz/default_plugin/tf_display.cpp
When introducing a new root TF frame, the corresponding root frame property of the TF display wasn't correctly re-parented, leaving two root frames:
=> TF display: Correctly reparent root frame property

src/rviz/default_plugin/point_cloud_common.cpp, src/test/point_cloud_test.py
This is the migration of #1652 to the `melodic` branch. The PR addresses the problem that a point cloud isn't smoothly moving if its `frame_id` is moving w.r.t. rviz' fixed frame.
The solution was to update the pose of the corresponding scene node in each `update()` cycle, not only when the message was received.
=> Smoothly update pose of point cloud on update()

src/rviz/mesh_loader.cpp, src/rviz/mesh_loader.h
This adds the functionality of importing an animated mesh to RViz using the same resource_retriever as in mesh_loader. 
Due to the way Ogre3D loads skeleton meshes a developer can automatically import an animated mesh using the same loadMeshFromResource method already present, but with the added functionality of assigning animation states.
The method is mostly the same as loadMeshFromResource but with changes to load the .skeleton file as well into the default resource group. 
Happy to accept any constructive critiques or suggestions on how to make it better!
- [Will do if accepted! ] Did you change how RViz works? Added new functionality? Do not forget to update the tutorials and/or …
=> Add skeleton import functionality to mesh_loader

src/rviz/default_plugin/axes_display.cpp, src/rviz/default_plugin/axes_display.h
Add the option to add a trail (`Ogre::RibbonTrail`) to the frame axes display. This replicates the "Show Trail" features from the `RobotModelDisplay`. This implements and fixes https://github.com/ros-visualization/rviz/issues/1627.
The ribbon trail will show the path a frame took. However, when the frame axes and ribbon trail is initialised, it will show a trail from the origin to where the frame is spawned. I am not sure if this intended behaviour that is also present in the `RobotModelDisplay` view.
Edi: I think the problem simply stems from the visualisation of the axes scene node which is rendered at the origin before the first frame pose has been received.
=> frame axes trail

src/rviz/mesh_loader.cpp
As pointed out by @simonschmeisser in https://github.com/ros-visualization/rviz/pull/1684#issuecomment-977827800, `assimp` should actually provide the correct scaling factor and it actually does: The scaling is embedded in the root node's transform, which was deliberately ignored.
Fixes #1665. @simonschmeisser and @peci1, could you please review and test?
=> Drop proprietary COLLADA scaling

src/rviz/mesh_loader.cpp
This is a fixup of #1685, fixing a regression revealed in #1688.
Looks like assimp's root node is only _sometimes_, but not always applying a rotation to y-up orientation.
This fixup, drops the rotation part of the root transform, but keeps the scaling (and position offset).
=> Fixup assimp mesh loading

src/rviz/robot/robot_link.cpp, src/rviz/robot/robot_link.h
Currently, rviz modifies a custom material setting loaded together with a mesh model, e.g. within [`updateAlpha()`](https://github.com/ros-visualization/rviz/blob/5531206e77d8092dbdb6a50a5b1a3c23fe5e181e/src/rviz/robot/robot_link.cpp#L390-L413).
This destroys, for example, transparency within those original materials.
With this pull request, the _original_ material is stored additionally to the _active_ one, such that the original one can be restored if needed. This allows to correctly render e.g. glass:
|  old                       |  new                     |
|-------------------------|------------------------|
| ![Screenshot from 2022-01-30 17-26-22](https://user-images.githubusercontent.com/4062443/151708047-7b83ef40-c9e6-41cb-bd10-d692f72a7bb1.png) | ![Screenshot from 2022-01-30 …
=> Maintain original mesh materials for RobotLinks

src/rviz/robot/robot.cpp, src/rviz/robot/robot_link.cpp, src/rviz/robot/robot_link.h
rviz::RobotLink knows 3 material modes, showing:
- original material of the mesh
- a user-selected color
- an error color (uniform white)
Switching between these modes requires iterating through all subentities of the link, 
which might be rather time-consuming. Also, this was done in each update() cycle!
This commit simplifies the handling, performing the costly update only if really necessary.
=> RobotLink: Simplify material mode handling

src/rviz/display.cpp, src/rviz/display.h
Fixes #1738
If an associated widget is tabbed and deselected, its visibility changes to false, which triggers disabling the display.
However, in this case, the widget is still there and thus the display shouldn't be disabled.
=> Don't disable display if associated widget tab changes

src/rviz/robot/robot_link.cpp
This is an alternative implementation to resolve duplicate material names (#1746)
=> Avoid cloning the original robot (mesh) link material

src/rviz/frame_manager.cpp, src/rviz/frame_manager.h, src/rviz/time_panel.cpp, src/rviz/time_panel.h, src/test/send_tf_timing.py, src/test/tf_sync_display.rviz, src/test/tf_sync_frame.rviz
... to sync TF lookups within the current rendering frame.
Fixes #1693. @AndreasR30, please review.
@dgossow, You implemented the _experimental_ `TimePanel` functionality 9 years ago. Unfortunately, there are no PR or code comments for the changeset 8c4cccf54a4581deff9d806d401b18a1a4411854 and I had a hard time guessing the intended functionality.
I understood that `SyncExact` and `SyncApprox` are intended to sync against a time signal provided by a specific source `Display`. For example, all displays deriving from `PointCloudCommon` call `emitTimeSignal()` and thus allow this functionality. However, I didn't get the intention of the `SyncApprox` mode. TF lookups perform an approximate lookup anyway, aren't they? So what's the role of `SyncApprox`?
As this mode essentially doesn't work …
=> Add new time sync mode SyncFrame

src/rviz/robot/robot_link.cpp, src/rviz/robot/robot_link.h
If a RobotLink has multiple visuals with different alpha values, only the last one was actually used (stored in `material_alpha_`).
Instead, store the original material and use alpha from there.
|before|after|
|------|--------|
| ![image](https://user-images.githubusercontent.com/5376030/171998783-0636ca0b-3e01-4d50-ad5b-31e09e587684.png) | ![image](https://user-images.githubusercontent.com/5376030/171998759-425c2be5-213c-4f3a-a6c3-4b656af04b25.png) |
=> Fix transparency of RobotLinks

src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h
When deleting a PanelDockWidget directly (i.e. not using the corresponding menu action), a dangling pointer was maintained (causing a crash e.g. on next Save) and the menu action wasn't removed. 
Now, if the dock is removed, the cleanup happens as well.
=> Fix panel deletion

src/rviz/properties/property_tree_delegate.cpp, src/rviz/properties/splitter_handle.cpp, src/rviz/properties/splitter_handle.h
Various fixes and improvements to the SplitterHandle used in PropertyTreeWidgets. Fixes #1758.
| before | after |
|----------|---------|
| ![image](https://user-images.githubusercontent.com/5376030/182017093-23214040-ba0e-4768-b45b-1c0d8fff7052.png) | ![image](https://user-images.githubusercontent.com/5376030/182017184-de507a1e-4e8d-4242-8313-20e7e848023a.png) |
=> Improve SplitterHandle of PropertyTreeWidgets

src/rviz/properties/property_tree_widget.cpp, src/rviz/properties/splitter_handle.cpp
Fixup for #1760
All issues essentially originate from horizontal scrolling. To avoid this, we need to:
- `setStretchLastSection(false)`
- decrease the shrinking column first before increasing the other one
- Consider `Resize` events of the viewport, not the `QTreeView` itself
- In case horizontal scrolling still occurs, have the scrollbar visible at least
=> Fixup SplitterHandle

src/rviz/main.cpp, src/rviz/visualization_frame.cpp, src/rviz/visualization_frame.h, src/rviz/visualizer_app.cpp, src/rviz/visualizer_app.h
This removes the need for the `setApp()` call.
As seen in the Qt [documentation](https://doc.qt.io/qt-5/qcoreapplication.html#processEvents) `processEvents` is a static function so no member of `QCoreApplication` is required. Removing this takes away the need for `setApp()` in `VisualizationFrame` and `VisualizerApp` which i have keept for now, but should be marked as deprecated and get removed in the future.
Removing this requirement of QApplication help to ease the step of integrating rviz into other possibly quite big Qt-Applications, if there is no need to pass around a pointer to the main Application.
=> use static QCoreApplication::processEvents() function without a QApplication instance.

src/rviz/default_plugin/tf_display.cpp, src/rviz/default_plugin/tf_display.h
When there is a lot of frames on `/tf` it can be hard to properly visualize them in RViz especially if frames overlap. Usually solution to this is to enable and disable desired frames in `Frames` field of the `TF display`. But it quickly become very annoying task if there is a lot of frames (e.g.  100 +) and each one needs to be found in a long list first and then disabled/enabled.
Because of that I suggest adding regex field which filters frames and displays only the ones matching entered expression. For convenience I also suggest adding additional field for blacklist filter.
Benefit of this approach is that user can quickly setup one or more displays, each showing specific group of frames and he can turn each one on/off as needed.
Scene with a lot of frames ...
... can be easily …
=> Added regex filter field for TF  display

src/rviz/default_plugin/tf_display.cpp, src/rviz/properties/property.cpp, src/rviz/properties/property.h
This improves the TF display in multiple ways:
- Insert all known frames to the tree (before only ones that were connected to rviz' global frame).  
This allows spotting disconnected trees in a glance.
- Ensure that frames are inserted in sorted fashion.
- Improve insertion and re-parenting of tree nodes
=> Several improvements to TF display

src/rviz/screenshot_dialog.cpp
Referring to the document below and based on the warnings I am getting at runtime, we replace QPixmap with QScreen:
https://doc.qt.io/qt-5/qpixmap-obsolete.html
Referring to the document below and based on the warnings I am getting at runtime, we replace QPixmap with QScreen:
https://doc.qt.io/qt-5/qpixmap-obsolete.html
(Unfortunately I am running this on Ubuntu 22.04 right now, and not my work PC where I was getting the error, and cannot compile ROS1 code here. How do I proceed?)
=> Replace obsolete QPixmap::grabWindow() with QScreen::grabWindow()

src/rviz/properties/property_tree_widget.cpp
Property might no longer exist when event is triggered
fixes #1657
=> call propertyHiddenChanged synchronously

src/rviz/default_plugin/map_display.cpp
When using the scene manager raycast in one of our tool rviz crashed when the tool touched the map area while a new map was received.
Apparently, the connection is not queued (anymore?) and therefore the update does not happen on the main thread.
This small change should fix this and is fully ABI compatible.
Fixes #1792
=> Fixed crash when raycasting while map is updated.

src/rviz/default_plugin/laser_scan_display.cpp, src/rviz/default_plugin/laser_scan_display.h, src/rviz/frame_manager.cpp
... to avoid issues like https://github.com/ros-visualization/rviz/issues/1796 in future.
=> Improve error handling in LaserScanDisplay

src/rviz/properties/property.cpp, src/rviz/properties/property_tree_model.cpp, src/rviz/properties/property_tree_widget.cpp
With Qt 5.15, the `Global Options` property was vanishing, when a `RobotModelDisplay` was added with links having no geometry. In this case, the `Alpha` property of the corresponding link is hidden.
However, hiding a property:
https://github.com/ros-visualization/rviz/blob/4129ee477ecd47b9c941d90cdf5e3e4f26fad835/src/rviz/properties/property.cpp#L398
during the process of reparenting:
https://github.com/ros-visualization/rviz/blob/4129ee477ecd47b9c941d90cdf5e3e4f26fad835/src/rviz/properties/property.cpp#L373
caused setRowHidden to be called with an invalid `parentIndex`:
https://github.com/ros-visualization/rviz/blob/4129ee477ecd47b9c941d90cdf5e3e4f26fad835/src/rviz/properties/property_tree_widget.cpp#L125
which then caused hiding of the corresponding top-level property.
=> Fix vanishing "Global Options" property when adding a RobotModelDisplay

src/rviz/default_plugin/tf_display.cpp
TF display was segfaulting when a loop was introduced in the `tree_category_`.
=> Gracefully handle loops in TF tree

src/rviz/default_plugin/map_display.cpp, src/rviz/default_plugin/map_display.h
The queued connection update introduced in #1793 caused the map display to first update the pose of the map and then the map itself (in the next update cycle). The resulting jittering can be perfectly seen when throttling the rviz frame rate.
Updates to the visualization should be handled in update() only. Thus, now, if a map update is received, a flag is set to perform the costly map update. If that flag is not set, only the transform is updated.
Fixes #1826
=> Fix #1826: jitter in Map display updates

src/rviz/properties/property.cpp
When a hidden property was configured to process `propertyHiddenChanged` and got deleted in between, this was causing a segfault. We need to protect the slot/functor from being called when the property is deleted.
Fixes #1830.
=> Fix #1825/#1830: segfault when hiding deleted properties

CMakeLists.txt
Noetic will be EOL very soon and it was already discussed what last changes would be worthwhile.
This was done in [Discourse](https://discourse.ros.org/t/ros-noetic-end-of-life-may-31-2025/43160/4) .
One point was the cmake_minimum_required version because <3.5 is deprecated in newer CMake version.
=> Bump cmake_minimum_required to avoid deprecation

src/rviz/main.cpp
When running on wayland with Ogre without wayland support, explicitly force Qt to use the XCB protocol running through Xwayland.
Backported with adaptations from https://github.com/ros2/rviz/issues/847 .
@rhaschke as discussed in person.
Tested on Debian trixie to run under X11 as well as wayland.
=> wayland fallback on X11-Ogre

src/rviz/image/image_display_base.cpp, src/rviz/image/image_display_base.h
With this PR, you can switch on `Reset When Timed Out` function, which makes image display show "No Image" again when new image has not been received for `Timeout` seconds.
This PR makes it easier to notice that the image publisher is in trouble.
https://github.com/user-attachments/assets/55ee0e1f-c0b3-45c2-9175-3067269e16ce
https://github.com/user-attachments/assets/366eac6f-f3e0-41c6-bc36-a80ac79daa44
Note that the default state of `Reset When Timed Out` is OFF, which leads to the same behavior before this PR.
=> Enable to reset image display when new image has not been received for a while
