src/rviz/default_plugin/wrench_display.cpp

Sometime position of wrench is set to nan, this patch is to avoid that issue

Check if position of wrench is not nan

---

src/rviz/default_plugin/wrench_display.cpp
src/rviz/default_plugin/wrench_display.h
src/rviz/default_plugin/wrench_visual.cpp
src/rviz/default_plugin/wrench_visual.h

See https://github.com/ros-visualization/rviz/pull/862

Forward port of pull request #862 to indigo-devel

---

src/rviz/ogre_helpers/stl_loader.cpp

This pull request is targeted to indigo-devel. #864

Updated version of pull request #864

---

src/rviz/ogre_helpers/stl_loader.cpp

Reverts ros-visualization/rviz#871

Revert "Updated version of pull request #864"

---

src/rviz/default_plugin/marker_display.cpp

See:
- http://answers.ros.org/question/205322/delete-all-rviz-markers/
- https://github.com/ros-visualization/rviz/issues/865
Fixes #865

Potential fix for DELETEALL marker action

---

src/rviz/visualizer_app.cpp

add option to start rviz with the ROS logger level set to Debug

---

src/rviz/visualization_frame.cpp
src/rviz/visualization_frame.h

override setStatusBar to avoid trying to use it when it is changed

---

src/rviz/tool_manager.cpp

remove shortkeys from shortkey_to_tool_map_

---

CMakeLists.txt

This replaces @tobiasberling's https://github.com/ros-visualization/rviz/pull/965.

fix cmake eigen warning

---

CMakeLists.txt
cmake/rviz-extras.cmake.in

The variable is called `rviz_QT_VERSION`.

export the Qt version used by rviz

---

src/rviz/default_plugin/marker_display.cpp
src/rviz/default_plugin/tf_display.cpp

backport of 988

---

src/rviz/default_plugin/wrench_display.cpp
src/rviz/default_plugin/wrench_display.h
src/rviz/default_plugin/wrench_visual.cpp
src/rviz/default_plugin/wrench_visual.h

see: https://github.com/ros-visualization/rviz/pull/982

forward port of 982

---

src/rviz/default_plugin/map_display.cpp

Replacement for https://github.com/ros-visualization/rviz/pull/963

[kinetic] Change costmap lethal color different from illegal values.

---

CMakeLists.txt

unify find_package(Qt)
quietly ignore failure of first find_package(Eigen3)

cmake cleanup

---

src/rviz/display_group.cpp
src/rviz/render_panel.cpp
src/rviz/visualization_manager.cpp

* fix ~RenderPanel()
unregister from scene_manager_
* VisualizationManager(): fix initialization order
* fix segfault
See: #1001

fix for two valgrind-reported issues (#1001)

---

src/rviz/displays_panel.cpp

Backport of https://github.com/ros-visualization/rviz/pull/1053

Fix double free in display dialog (#1053)

---

src/rviz/properties/float_edit.cpp

Backport of https://github.com/ros-visualization/rviz/pull/1043

bugfix in float_edit for non-english locales  (#1043)

---

CMakeLists.txt
package.xml
src/rviz/default_plugin/effort_display.cpp
src/rviz/default_plugin/effort_visual.cpp
src/rviz/robot/robot.cpp
src/rviz/robot/robot.h
src/rviz/robot/robot_joint.cpp
src/rviz/robot/robot_joint.h
src/rviz/robot/robot_link.cpp
src/rviz/robot/robot_link.h

See: https://github.com/ros-visualization/rviz/pull/1044#issuecomment-246720694

Revert "Use urdf::*ShredPtr instead of boost::shared_ptr"

---

src/rviz/robot/robot_joint.cpp
src/rviz/robot/robot_joint.h

Show joint properties in left hand panel and optionally show joint axis as arrow in the 3d view.

Visualize joint axis and display type and limits

---

src/rviz/robot/robot_link.cpp
src/rviz/robot/robot_link.h

this is rewrited version of #812 for indigo

support multiple material for one link

---

src/rviz/default_plugin/map_display.cpp
src/rviz/default_plugin/map_display.h

replacement for https://github.com/ros-visualization/rviz/pull/1007

Kinetic big maps

---

src/rviz/ogre_helpers/render_system.cpp
src/rviz/ogre_helpers/render_system.h
src/rviz/ogre_helpers/render_widget.cpp

Just opening this to look at the diff for now.

Osx ogre 1 9

---

src/rviz/default_plugin/covariance_visual.cpp
src/rviz/default_plugin/covariance_visual.h

See: http://build.ros.org/job/Kbin_dj_dJ64__rviz__debian_jessie_amd64__binary/50/console

attempt to fix debian jessie

---

package.xml

Backported from `kinetic-devel`.

Add dhood as maintainer (#1131)

---

src/rviz/default_plugin/odometry_display.cpp

Check for odometry quaternion normalization before display

---

README.md

Adresses #1147
@chadrockey @k-okada @jkammerl FYI

add copyright notice for icons and graphics

---

src/rviz/ogre_helpers/movable_text.cpp

Fixed use of LineSpacing, horizontal alignment and AABB calculation in MovableText

---

src/rviz/default_plugin/image_display.h

replacement of https://github.com/ros-visualization/rviz/pull/1161

allow classes inheriting from image display access to more state

---

src/rviz/default_plugin/effort_display.cpp
src/rviz/default_plugin/effort_display.h

Simple PR to add a TF Prefix property to the Effort Plugin.
Use case : `/robot1/robot_description` + `tf_prefix` set to `robot1`
~Also fixes #892.~

add TF Prefix to effort plugin and fix #892

---

README.md

I also added the waffle.io badge.

fix formatting of README.md

---

src/rviz/add_display_dialog.cpp
src/rviz/default_plugin/camera_display.cpp
src/rviz/default_plugin/depth_cloud_mld.cpp
src/rviz/default_plugin/effort_display.cpp
src/rviz/default_plugin/interactive_marker_display.cpp
src/rviz/default_plugin/interactive_markers/interactive_marker_control.cpp
src/rviz/default_plugin/map_display.cpp
src/rviz/default_plugin/point_cloud_common.cpp
src/rviz/default_plugin/point_cloud_transformers.cpp
src/rviz/render_panel.cpp
src/rviz/robot/robot.cpp
src/rviz/robot/robot_joint.cpp
src/rviz/robot/robot_link.cpp
src/rviz/selection/selection_manager.cpp
src/rviz/visualization_frame.cpp
src/test/new_display_dialog_test.cpp

This PR fixes several compiler warnings cluttering my console...

fix gcc warnings

---

src/rviz/visualization_frame.cpp
src/rviz/visualization_manager.cpp

Tracking down https://github.com/ros/resource_retriever/pull/27, I also stumbled over these small leaks.

fixed two minor memory leaks

---

doc/index.rst
mainpage.dox
package.xml
plugin_description.xml
src/rviz/visualization_frame.cpp

From http://ros.org/wiki to http://wiki.ros.org/
```
find . -type f -exec sed -i 's/http\:\/\/www\.ros\.org\/wiki/http\:\/\/wiki\.ros\.org/g' {} +
grep -rn "http://www.ros.org/wiki"
```

Update wiki URLs

---

src/rviz/default_plugin/effort_display.cpp

effort plugin: fix typo.

---

src/rviz/ogre_helpers/render_widget.cpp
src/rviz/render_panel.cpp

Code cleanups from https://github.com/ros-visualization/rviz/pull/1210

Small code cleanup

---

src/rviz/default_plugin/path_display.cpp
src/test/send_path.py

Orientations were not being transformed into fixed frame in the Path plugin.

Transform poses in Path message correctly into fixed frame.

---

src/rviz/default_plugin/view_controllers/fps_view_controller.cpp
src/rviz/frame_position_tracking_view_controller.h
src/rviz/render_panel.cpp
src/rviz/view_manager.cpp

Several small fixes to view controllers.

Cleanup view controllers

---

src/rviz/default_plugin/covariance_visual.h

Fix https://github.com/ros-visualization/rviz/issues/1311

public CovarianceVisual

---

src/rviz/default_plugin/effort_visual.cpp

Fixes https://github.com/ros-visualization/rviz/issues/811#issuecomment-388306367

EffortDisplay: ignore invalid effort values

---

src/rviz/default_plugin/marker_utils.cpp

Handle invalid floats in points of arrow marker

---

CMakeLists.txt
package.xml
src/rviz/CMakeLists.txt
src/rviz/visualization_frame.cpp
src/rviz/visualization_frame.h
src/rviz/visualizer_app.cpp
src/rviz/visualizer_app.h
srv/SendFilePath.srv

Rebase of #1250 against Melodic.

Provide load_config and save_config ROS services

---

src/rviz/default_plugin/tools/goal_tool.cpp
src/rviz/default_plugin/tools/initial_pose_tool.cpp
src/test/marker_test.cpp
src/test/rviz_logo_marker.cpp

Fix https://github.com/ros-visualization/rviz/issues/1509#
The wrong TF2 conversion was used

fix initial pose and goal buttons

---

package.xml

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
Move William from a maintainer to an author.  Once this is approved and merged, I'll open similar PRs for the melodic-devel and kinetic-devel branches.

Move William to an author.

---

src/rviz/default_plugin/screw_display.cpp
src/rviz/default_plugin/screw_display.h

ScrewDisplay: fix creation of properties

---

src/rviz/displays_panel.cpp
src/rviz/properties/color_editor.cpp
src/rviz/visualization_frame.cpp
src/rviz/visualizer_app.cpp
src/test/new_display_dialog_test.cpp

Keep ColorDialog on top of main window

---

src/rviz/visualization_frame.cpp
src/rviz/visualization_frame.h
src/rviz/window_manager_interface.h

https://github.com/ros-visualization/rviz/issues/1605
Fix add a new image panel but it's image didn't display correctly problem.

Add new imagepanel, but it doesn't display correctly. #1605

---

src/rviz/ogre_helpers/billboard_line.cpp

For a small number of total points, we place several lines into a single `Ogre::BillboardChain`.
However, if we have more than `MAX_ELEMENTS` points in a line, we need to distribute a line across several BillBoardChains.
Fixes #1107

BillboardLine: Fix handling of many points (> 16384)

---

src/rviz/default_plugin/point_visual.cpp

Fix scaling of PointVisual's sphere

---

src/rviz/ogre_helpers/movable_text.cpp

MovableText: gracefully handle string of whitespaces

---

src/rviz/mesh_loader.cpp

mesh loader: re-add transform of mesh normals

---

src/rviz/tool_manager.cpp

Fix segfault when no tools are available

---

README.md

Migrate melodic urls to noetic
Not relevant

(README) Migrate melodic urls to noetic

---

src/image_view/image_view.cpp
src/rviz/default_plugin/camera_display.cpp
src/rviz/default_plugin/image_display.cpp
src/test/send_images.cpp

Fixes #1762 resulting from texture wrapping. Switching to clamping fixes the problem.

Fix image display wrapping

---

src/rviz/message_filter_display.h

PointStampedDisplay: Ignore incoming messages if disabled

---

src/rviz/robot/robot_joint.cpp

Fix orientation of joint axis arrow

---

src/rviz/default_plugin/screw_display.cpp

Fix screw display

---

src/rviz/default_plugin/camera_display.cpp
src/rviz/default_plugin/image_display.cpp
src/rviz/default_plugin/image_display.h
src/rviz/panel_dock_widget.cpp
src/rviz/panel_dock_widget.h

toggle fullscreen button for ImageDisplay
